### ISSUE TITLE
HSPI vs SD Card Mail Client

### ISSUE THREAD

**Issue by Ddh012345dhD** [mobizt/ESP-Mail-Client#110]
How to use HSPI on ESP32 for SD card and Mail Client library?

**Comment by mobizt** [comment]
I check the source of ESP32 SPIClass and it initiate with HSPI bus already and you can config the pins with **MailClient.sdBegin**.

**Comment by Ddh012345dhD** [comment]
hi Suwatchai
thanks you support for me.

Although the SD card is successfully booted,when using another SPI bus
for another task, no data is received from that task. I think you
should add a separate SPI Class for the user to set up.


Vào Th 7, 30 thg 10, 2021 vào lúc 20:33 Suwatchai K. <
***@***.***> đã viết:

**Comment by mobizt** [comment]
The VSPI and HSPI is no different only pin assignment are different and you can change it by that sdBegin.

**Comment by mobizt** [comment]
Did you want custom SPI settings e.g. clock speed and mode? 

Because the default setting of SPI the SPIClass object is enough for fast and reliable access to most SD modules.

Can you provide that use case, I will consider to add this option if it is reasonable because the SPI setting is out of library control and it needed to keep the copy of user defined SPIClass object for further internal uses.

**Comment by mobizt** [comment]
If the default SPI setting is enough, no reason to define the local SPIClass object (SPI driver) to handle the SPI connection that can't work with other SPIClass object instances that declared global or as static.

**Comment by mobizt** [comment]
This is what I mean the static or global defined of SPIClass object with default setting.
https://github.com/espressif/arduino-esp32/blob/caa8d07aafa04441bb85e6046a795249c01d9e39/libraries/SPI/src/SPI.h#L89

**Comment by Ddh012345dhD** [comment]
My configuration is as follows:
#define lora_sck 18
#define lora_miso 19
#define lora_mosi 23
#define lora_cs 5
#define lora_rst 4
#define lora_irq 16
#define SD_CS 15
#define SD_SCK 14
#define SD_MOSI 12
#define SD_MISO 13
void lora_Config()
{
 LoRa.setPins(lora_cs, lora_rst, lora_irq);
  if (!LoRa.begin(fre)) {             // initialize ratio at 915 MHz
    Serial.println("LoRa init failed. Check your connections.");
    delay(5000);
    //ESP.restart();
  }
  LoRa.setTxPower(20);
  LoRa.onReceive(onReceive);
  LoRa.receive();
  LoRa.enableCrc();
  Serial.println("LoRa init succeeded.");
}
void SD_setup()
{
   if (!MailClient.sdBegin(SD_SCK,SD_MISO,SD_MOSI,SD_CS))
Serial.println("SD Card: mounting failed.");
   else Serial.println("SD Card: mounted.");
}

if i call SD_setup() before lora_Config() in setup() then SD mounted ,Lora
failed and vice versa.
Can you check this configuration for me?Please!

Vào Th 3, 2 thg 11, 2021 vào lúc 11:16 Suwatchai K. <
***@***.***> đã viết:

**Comment by mobizt** [comment]
This is not related to the library and I can't help in this use case as this is the two SPI buses configuration which you can avoid this to use the same share SPI bus instead.

**Comment by mobizt** [comment]
If you use multiple device on the same SPI bus, make sure MISO pin for that SPI module is driven by the tri-state buffer to release the bus when it inactive or disabled.
https://www.pjrc.com/better-spi-bus-design-in-3-steps/

**Comment by Ddh012345dhD** [comment]
I solved my problem. Thanks you so much @bro!

[image: image.png]

   -



Vào Th 3, 2 thg 11, 2021 vào lúc 13:53 Suwatchai K. <
***@***.***> đã viết:
