### ISSUE TITLE
Corruption of const char * variables after smtp.connect(&session)

### ISSUE THREAD

**Issue by saman-taghipour** [mobizt/ESP-Mail-Client#12]
Hi,
Node MCU, ESP-12E
I have several const char * variables in my code. These variables work well in the other part of code. When I want to send email, after this line: if (!smtp.connect(&session))
or line 148 of here: https://github.com/mobizt/ESP-Mail-Client/blob/master/examples/Send_HTML/Send_HTML.ino
const char * variables value are corrupted.

**Comment by mobizt** [comment]
All function parameters of this library are pointer to the variable which you need to keep  that variables in the usage scope of function.

You may declare these variable out of any code block at the top of your sketch and use it everywhere without any problem.

**Comment by saman-taghipour** [comment]
I declared const char * variables at the top of my sketch (global variable)
and I can access these variables in any other functions.
In this function that I want to send email, at first I can access these variables too. but after a line, any const chat * variables are corrupted
this line:

[here I can access const char * variables]
/* Connect to server with the session config */
    if (!smtp.connect(&session))
      return;
[here I can not access const char * variables]

**Comment by mobizt** [comment]
No one known your error without code. 
It's better to learn more about pointer in C or C++.

**Comment by saman-taghipour** [comment]
/**
 * This example will send the Email in
 * the html version.
 * 
 * 
 * Created by K. Suwatchai (Mobizt)
 * 
 * Email: suwatchai@outlook.com
 * 
 * Github: https://github.com/mobizt/ESP-Mail-Client
 * 
 * Copyright (c) 2020 mobizt
 *
*/

//To use send Email for Gmail to port 465 (SSL), less secure app option should be enabled. https://myaccount.google.com/lesssecureapps?pli=1
#include <LittleFS.h>
#include <ESP8266WiFi.h>
#include <ArduinoJson.h>
#include <ESP_Mail_Client.h>

WiFiClient client;

#define WIFI_SSID "mySSID"
#define WIFI_PASSWORD "myPresharedkey"

/** The smtp host name e.g. smtp.gmail.com for GMail or smtp.office365.com for Outlook or smtp.mail.yahoo.com
 * For yahoo mail, log in to your yahoo mail in web browser and generate app password by go to
 * https://login.yahoo.com/account/security/app-passwords/add/confirm?src=noSrc
 * and use the app password as password with your yahoo mail account to login.
 * The google app password signin is also available https://support.google.com/mail/answer/185833?hl=en
*/
#define SMTP_HOST "smtp.gmail.com"

/** The smtp port e.g. 
 * 25  or esp_mail_smtp_port_25
 * 465 or esp_mail_smtp_port_465
 * 587 or esp_mail_smtp_port_587
*/
#define SMTP_PORT 465

/* The log in credentials */
#define AUTHOR_EMAIL "userName@gmail.com"
#define AUTHOR_PASSWORD "appPassword"

/* The SMTP Session object used for Email sending */
SMTPSession smtp;

String publicIP;

/* Callback function to get the Email sending status */
void smtpCallback(SMTP_Status status);

const char * var;

void setup()
{
  Serial.begin(9600);
  LittleFS.begin();
  Serial.println();

  Serial.print("Connecting to AP");

  WiFi.begin(WIFI_SSID, WIFI_PASSWORD);
  while (WiFi.status() != WL_CONNECTED)
  {
    Serial.print(".");
    delay(200);
  }

  Serial.println("");
  Serial.println("WiFi connected.");
  Serial.println("IP address: ");
  Serial.println(WiFi.localIP());
  Serial.println();
  readVarFromFile();


  /** Enable the debug via Serial port
   * none debug or 0
   * basic debug or 1
  */
  smtp.debug(1);

  /* Set the callback function to get the sending results */
  smtp.callback(smtpCallback);

  /* Declare the session config data */
  ESP_Mail_Session session;

  /* Set the session config */
  session.server.host_name = SMTP_HOST;
  session.server.port = SMTP_PORT;
  session.login.email = AUTHOR_EMAIL;
  session.login.password = AUTHOR_PASSWORD;
  session.login.user_domain = "mydomain.net";

  /* Declare the message class */
  SMTP_Message message;

  /* Set the message headers */
  message.sender.name = "Saman";
  message.sender.email = AUTHOR_EMAIL;
  message.subject = "mySubject";
  message.addRecipient("Someone", "Recipient@gmail.com");
  String str55 = "test message";
  message.html.content = str55.c_str();

  /** The html text message character set e.g.
   * us-ascii
   * utf-8
   * utf-7
   * The default value is utf-8
  */
  message.html.charSet = "us-ascii";

  /** The content transfer encoding e.g.
   * enc_7bit or "7bit" (not encoded)
   * enc_qp or "quoted-printable" (encoded)
   * enc_base64 or "base64" (encoded)
   * enc_binary or "binary" (not encoded)
   * enc_8bit or "8bit" (not encoded)
   * The default value is "7bit"
  */
  message.html.transfer_encoding = Content_Transfer_Encoding::enc_base64;

  /** The message priority
   * esp_mail_smtp_priority_high or 1
   * esp_mail_smtp_priority_normal or 3
   * esp_mail_smtp_priority_low or 5
   * The default value is esp_mail_smtp_priority_low
  */
  message.priority = esp_mail_smtp_priority::esp_mail_smtp_priority_low;

  /** The Delivery Status Notifications e.g.
   * esp_mail_smtp_notify_never
   * esp_mail_smtp_notify_success
   * esp_mail_smtp_notify_failure
   * esp_mail_smtp_notify_delay
   * The default value is esp_mail_smtp_notify_never
  */
  message.response.notify = esp_mail_smtp_notify_success | esp_mail_smtp_notify_failure | esp_mail_smtp_notify_delay;

  /* Set the custom message header */
  message.addHeader("Message-ID: <abcde.fghij@gmail.com>");
  
  Serial.print("Variable is(second read): ");
  Serial.println(var);
  // here variable is correct
  
  /* Connect to server with the session config */
  if (!smtp.connect(&session))
    return;
  Serial.print("Variable is(third read): ");
  Serial.println(var);
  // here variable is corroupted *************************************************
  /* Start sending Email and close the session */
  if (!MailClient.sendMail(&smtp, &message))
    Serial.println("Error sending Email, " + smtp.errorReason());
}

void loop()
{
}

/* Callback function to get the Email sending status */
void smtpCallback(SMTP_Status status)
{
  /* Print the current status */
  Serial.println(status.info());

  /* Print the sending result */
  if (status.success())
  {
    Serial.println("----------------");
    Serial.printf("Message sent success: %d\n", status.completedCount());
    Serial.printf("Message sent failled: %d\n", status.failedCount());
    Serial.println("----------------\n");
    struct tm dt;

    for (size_t i = 0; i < smtp.sendingResult.size(); i++)
    {
      /* Get the result item */
      SMTP_Result result = smtp.sendingResult.getItem(i);
      localtime_r(&result.timesstamp, &dt);

      Serial.printf("Message No: %d\n", i + 1);
      Serial.printf("Status: %s\n", result.completed ? "success" : "failed");
      Serial.printf("Date/Time: %d/%d/%d %d:%d:%d\n", dt.tm_year + 1900, dt.tm_mon + 1, dt.tm_mday, dt.tm_hour, dt.tm_min, dt.tm_sec);
      Serial.printf("Recipient: %s\n", result.recipients);
      Serial.printf("Subject: %s\n", result.subject);
    }
    Serial.println("----------------\n");
  }
}

void readVarFromFile(){
  File myFile16 = LittleFS.open("Variables.txt", "r");
  String abc = myFile16.readString();
  Serial.print("Variable abc is: ");
  Serial.println(abc);
  DynamicJsonBuffer jsonBuffer16;
  JsonObject& json16 = jsonBuffer16.parseObject(abc);
  if(!json16.success()){
    delay(1000);
    Serial.println("ERROR in readVarFromFile()");
    return;
  }
  var = json16["var1"];
  myFile16.close();
  // here variable is correct
  Serial.print("Variable is(first read): ");
  Serial.println(var);
}

**Comment by saman-taghipour** [comment]
this variable is correct in every function
but after this line:
if (!smtp.connect(&session))
return;

it is corroupted!!!
