### ISSUE TITLE
README config value typo

### ISSUE THREAD

**Issue by NoahSommerfeld** [mobizt/ESP-Mail-Client#124]
**Build tool used:**

- [X ] Arudino
- [ ] Platformio (Visual Studio Code plugin)
- [ ] Platformio CLI
- [ ] Other

**Board used (ESP32/ESP8266/Arudino):**

- [X ] ESP8266-based
- [ ] ESP32-based

**Other Libraries That are used:**

n/a

**Description of problem:**
The Function definition README (https://github.com/mobizt/ESP-Mail-Client/blob/master/src/README.md) has the same description for 'attachment_size' limit config value and ' imap_idle_timeout'. Unless I'm mistaken, imap_idle_timeout is not related to attachment size, and the other text (circled red below) should be the description instead. 

For context I was looking to understand the behavior of the 'listen' function to confirm if it implemented IMAP's Idle command (and by extension confirm I had found the right way to avoid hammering Office365 with polling, which I do believe this function correctly avoids doing. )

**Share code snippet to reproduce the issue:**
Screenshot of the readme page with the identical value descriptions highlighted
![image](https://user-images.githubusercontent.com/7077613/147627891-672851e5-c32a-44ef-827e-f0f840b1674c.png)

**Additional information and things you've tried:**
Thanks for this great library and examples!

**Comment by mobizt** [comment]
Thanks for report this issue.

Now I update the Readme already
https://github.com/mobizt/ESP-Mail-Client/blob/master/src/README.md#size_t-imap_idle_timeout---the-imap-idle-timeout-in-ms
