### ISSUE TITLE
Incorrect Arduino IDE addition instructions

### ISSUE THREAD

**Issue by mArvidsson** [mobizt/ESP-Mail-Client#126]
Hi! I just wanted to outline for others, the instructions to add the library to Arduino IDE are incorrect.

1. Download the ZIP file.
2. Extract to folder
3. Rename folder from "ESP-Mail-Client-master" to "ESP_Mail_Client"
4. Re-zip your new folder to "ESP_Mail_Client.zip". (NOTE: Folder should be in top directory, not files.)
5. Now you can import ZIP-library!

This because the srcs files that Arduino IDE looks for should match the ZIP/folder names.. And with -master or dashes it simply does not work!

**Comment by mobizt** [comment]
Thanks

**Comment by mobizt** [comment]
There is no need to do that.
