### ISSUE TITLE
I had to remove all the F() macros to get it to work.

### ISSUE THREAD

**Issue by koolwood** [mobizt/ESP-Mail-Client#142]
**Build tool used:**

- [x ] Arudino
- [ ] Platformio (Visual Studio Code plugin)
- [ ] Platformio CLI
- [ ] Other

**Board used (ESP32/ESP8266/Arudino):**

- [x ] ESP8266-based
- [ ] ESP32-based

**Other Libraries That are used:**

In "Send_Text.ino" example I had to remove all the F() macros to get it to work.  Once I did that is sent the email just fine.
Those are the only changes I made to the example code other network and email requirements.
I am not sure it is a bug because I could have something in the IDE set wrong but for not it works.

**Description of problem:**

**Share code snippet to reproduce the issue:**
```yaml
PASTE .cpp / .ino code here

//  session.time.ntp_server = F("pool.ntp.org,time.nist.gov");
  session.time.ntp_server = "pool.ntp.org,time.nist.gov";
```

**Additional information and things you've tried:**

**Comment by koolwood** [comment]
I also had to do the same thing in Send_Attachment_File example.

**Comment by mobizt** [comment]
This is the esp8266 core issue about flash string pointer which you may need to update the SDK too.

I will fix this on library side too.

**Comment by koolwood** [comment]
Thanks for the response.  I think the F() macro works with the String class because I have used that in other programs.For now I have something that works.  
Thanks for the library.
    On Tuesday, January 25, 2022, 10:02:47 PM EST, Suwatchai K. ***@***.***> wrote:  
 
 


This is the esp8266 core issue about flash string pointer which you may need to update the SDK too.

I will fix this on library side too.

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
