### ISSUE TITLE
readMail fails on empty mailbox or if no matching messages are found

### ISSUE THREAD

**Issue by dkalliv** [mobizt/ESP-Mail-Client#15]
If the selected folder (for example INBOX) is empty or no message matches the search pattern, readMail fails after the ESP_MAIL_DEFAULT_TCP_TIMEOUT_SEC timeout of 30 seconds.

**Comment by mobizt** [comment]
Thanks for inform this issue.

The issue was fixed in the latest update. 

Please update.
