### ISSUE TITLE
Problem with ISO-8859-1 encoded subject header fields

### ISSUE THREAD

**Issue by dkalliv** [mobizt/ESP-Mail-Client#154]
**Build tool used:**

- [x] Arudino
- [ ] Platformio (Visual Studio Code plugin)
- [ ] Platformio CLI
- [ ] Other

**Board used (ESP32/ESP8266/Arudino):**

- [ ] ESP8266-based
- [x] ESP32-based

**Other Libraries That are used:**

**Description of problem:**
Message subjects that are ISO-8859-1 encoded are not decoded correctly if the encoding scheme is provided in uppercase letters (same gmail apps on Android seem to be doing this). See sample message header snippet.

**Share code snippet to reproduce the issue:**
```yaml
Subject: =?ISO-8859-1?B?5Pb8?=

```

**Additional information and things you've tried:**
I fixed the problem by converting headerEnc to lowercase. I've created a pull request with the fix.

**Comment by mobizt** [comment]
Can you update the pull request based on my comment?
