### ISSUE TITLE
NTP server timeout - Error, NTP server time synching timed out

### ISSUE THREAD

**Issue by marmou-fritzing** [mobizt/ESP-Mail-Client#173]
**Build tool used:**

- [ ] Arudino
- [ ] Platformio (Visual Studio Code plugin)
- [ ] Platformio CLI
- [X] Other
PROGRAMINO IDE

**Board used (ESP32/ESP8266/Arudino):**

- [ ] ESP8266-based
- [X] ESP32-based
LilyGo TTGO T-call & PMU: http://www.lilygo.cn/claprod_view.aspx?TypeId=21&Id=1285&FId=t28:21:28

**Other Libraries That are used:**

#include <Arduino.h>
#include <string.h>
#include <FS.h>
#include <SD.h>
#include <SPIFFS.h>
#include <Update.h>
#include <SPI.h>
#include <Wire.h>
#include <OneWire.h>
#include <DallasTemperature.h>
#include <WiFi.h>
#include <HTTPClient.h> // HTTP client I use for loging values to cloud.
#include <ESP32Ping.h>
#include <ESP_Mail_Client.h>
#include <EEPROM.h>
#include <Adafruit_GFX.h>
#include <Adafruit_SSD1306.h>
#include <axp20x.h> // Power management
#include <PCF8574.h> // Port expander

**Description of problem:**
After last actualisation always happens, that NTP server is not available or don't answer so quick, as is necessary. Here is report of Email client debug and callback:
On older library happens the same (what I remember) only one time.

Connecting to SMTP server...
> C: ESP Mail Client v2.2.2
> C: Wait for NTP server time synching
Error, NTP server time synching timed out
> E: NTP server time synching timed out
> C: Connect to SMTP server
> C: Host > smtp.gmail.com
> C: Port > 465
> C: starting socket
> C: connecting to Server
> C: seeding the random number generator
> C: setting up the SSL/TLS structure
! W: Skipping SSL Verification. INSECURE!
> C: setting hostname for TLS session
> C: performing the SSL/TLS handshake
> C: verifying peer X.509 certificate
> C: SMTP server connected
SMTP server connected, wait for greeting...
< S: 220 smtp.gmail.com ESMTP lv15-20020a170906bc8f00b006f3ef214dfcsm1904077ejb.98 - gsmtp
Sending greeting response...
> C: Send SMTP command, HELO
< S: 250-smtp.gmail.com at your service, [85.71.29.47]
< S: 250-SIZE 35882577
< S: 250-8BITMIME
< S: 250-AUTH LOGIN PLAIN XOAUTH2 PLAIN-CLIENTTOKEN OAUTHBEARER XOAUTH
< S: 250-ENHANCEDSTATUSCODES
< S: 250-PIPELINING
< S: 250-CHUNKING
< S: 250 SMTPUTF8
Logging in...
> C: Send SMTP command, AUTH PLAIN
> C: hvnmail.1@gmail.com
> C: hvnmail.1@gmail.com ****************
< S: 235 2.7.0 Accepted
> C: Send Email
Sending message header...
> C: Send message header
< S: 250 2.1.0 OK lv15-20020a170906bc8f00b006f3ef214dfcsm1904077ejb.98 - gsmtp
< S: 250 2.1.5 OK lv15-20020a170906bc8f00b006f3ef214dfcsm1904077ejb.98 - gsmtp
Sending message body...
> C: Send message body
< S: 354  Go ahead lv15-20020a170906bc8f00b006f3ef214dfcsm1904077ejb.98 - gsmtp
Finishing the message sending...
> C: Finish the message sending
< S: 250 2.0.0 OK  1652351524 lv15-20020a170906bc8f00b006f3ef214dfcsm1904077ejb.98 - gsmtp
Closing the session...
> C: Terminate the SMTP session
< S: 221 2.0.0 closing connection lv15-20020a170906bc8f00b006f3ef214dfcsm1904077ejb.98 - gsmtp
Message sent successfully
> C: Message sent successfully
Sent: 1
> C: cleaning SSL connection

**Share code snippet to reproduce the issue:**
```yaml
PASTE .cpp / .ino code here

            if(PoradiSekvenceOdesliEmailWiFi == 0){
               String PredmetEmailu; //Subject of e-mail
               PocetOpakovaniPrikazuWiFi = 0; // Num of iteration of try send it
               OdeselPrikazDoWIFI        = true; // Locking variable to "No make something else with Wifi "(used in other part of program)
               // ------------------- PŘÍPRAVA ZPRÁVY ---------------------
               session.server.host_name  = AdresaSMTPServeru;
               session.server.port       = PortSMTPServeru;
               session.login.email       = EmailZarizeni;
               session.login.password    = HesloEmailZarizeni;
               session.login.user_domain = "";
               
               if(KodEmailu.substring(0,2) == "EN"){ // Setting of e-mail header and body depended on issue character
                  message.subject = PredmetEmailuNapajeni;
                  PredmetEmailu   = PredmetEmailuNapajeni;
                  TextEmailu      = TextEmailuNapajeni;
               }else if(KodEmailu.substring(0,2) == "EB"){
                  message.subject = PredmetEmailuBaterie;
                  PredmetEmailu   = PredmetEmailuBaterie;
                  TextEmailu      = TextEmailuBaterie;
               }else if(KodEmailu.substring(0,2) == "ET"){
                  message.subject = PredmetEmailuTeplota;
                  PredmetEmailu   = PredmetEmailuTeplota;
                  TextEmailu      = TextEmailuTeplota;
               }else if(KodEmailu.substring(0,2) == "ES"){
                  message.subject = PredmetEmailuKvalitaSignalu;
                  PredmetEmailu   = PredmetEmailuKvalitaSignalu;
                  TextEmailu      = TextEmailuKvalitaSignalu;
               }
               message.sender.name  = NazevZarizeniEmail;
               message.sender.email = EmailZarizeni;
               message.addRecipient("", EmailAdresata); 
               message.html.charSet = "utf-8";
               message.html.transfer_encoding = Content_Transfer_Encoding::enc_7bit;
               message.priority = esp_mail_smtp_priority::esp_mail_smtp_priority_high;
               message.response.notify = esp_mail_smtp_notify_never;
               TextEmailu = "<!DOCTYPE html><html><head><meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\"><meta http-equiv=\"Content-Transfer-Encoding\" encoding=\"quoted-printable\"><title>" + PredmetEmailu + "</title></head><body>" + TextEmailu + "</body></html>";
               message.html.content          = TextEmailu.c_str();
               PoradiSekvenceOdesliEmailWiFi = 1;
            }else if(PoradiSekvenceOdesliEmailWiFi == 1){
               if(PocetOpakovaniPrikazuWiFi > 2){
                  smtp.sendingResult.clear();
                  message.clear();
                  OdesliEmail                   = false;
                  OdeselPrikazDoWIFI            = false; // Unlocking WIFI next commands
                  PoradiSekvenceOdesliEmailWiFi = 0;
                  VyresHlaseniWIFIEmailem(4); // Routine for Logging of e-mail sending results (write numbers to byte array)
               }else{
                  ledcWrite(Kanal, 0);
                  if (!smtp.connect(&session)){
                     VyresHlaseniWIFIEmailem(4);
                     OdeselPrikazDoWIFI = false; // Unlocking WIFI next commands
                     if(smtp.closeSession() == true){
                     }else{
                     }
                     PoradiSekvenceOdesliEmailWiFi = 0;
                     PocetOpakovaniPrikazuWiFi     = 0;
                     message.clear();
                     smtp.sendingResult.clear();
                     PocetOpakovaniPrikazuWiFi++;
                  }else{
                     VyresHlaseniWIFIEmailem(1);
                     ledcWrite(Kanal, 0);
                     PoradiSekvenceOdesliEmailWiFi = 2;
                  }
               }
            }else if(PoradiSekvenceOdesliEmailWiFi == 2){
               // ------------------- ODESLÁNÍ ZPRÁVY ---------------------
               if(PocetOpakovaniPrikazuWiFi > 2){
                  message.clear();
                  smtp.sendingResult.clear();
                  OdesliEmail                   = false;
                  OdeselPrikazDoWIFI            = false; // Unlocking WIFI next commands
                  PoradiSekvenceOdesliEmailWiFi = 0;
                  VyresHlaseniWIFIEmailem(4);
               }else{
                  if (!MailClient.sendMail(&smtp, &message, true)){
                     OdeselPrikazDoWIFI = false; // Unlocking WIFI next commands
                     if(smtp.closeSession() == true){
                     }else{
                     }
                     PoradiSekvenceOdesliEmailWiFi = 0;
                     VyresHlaseniWIFIEmailem(4);
                     PocetOpakovaniPrikazuWiFi++;
                  }else{
                     PoradiSekvenceOdesliEmailWiFi = 3;
                     VyresHlaseniWIFIEmailem(2);
                  }
               }
            }else if(PoradiSekvenceOdesliEmailWiFi == 3){
               // ------------------- ČIŠTĚNÍ ---------------------
               smtp.sendingResult.clear();
               message.clear();
               OdesliEmail                   = false; // Sending finished, cycle already will not continue
               OdeselPrikazDoWIFI            = false; // Unlocking WIFI next commands
               PoradiSekvenceOdesliEmailWiFi = 0;
            }
```

**Additional information and things you've tried:**
Only notice: Because sending of e-mail takes some time and device is in this time busy and I need to be subroutine for e-mail works simoutaneously with other parts of program, sequence is separated to 4 steps, guided by "PoradiSekvenceOdesliEmailWiFi" variable.
Variables (objects) session and message are defined like a global variables.
I tried find on internet any methode how immediately after start device and connected it to the internet, synchronise time. I'v found nothing. :-( I don'T know what it happens automatically and whether is it necessary.

**Comment by mobizt** [comment]
If your device time does not set or sync with NTP server before calling `smtp.connect(&session))`, the library will sync or set the device time with NTP server internally and if the time was not sync within 10 seconds, the error NTP time sync timed out will print out.

This is already written in the example comment.

https://github.com/mobizt/ESP-Mail-Client/blob/68b90789f522db7170eb3ace7129efce3d388949/examples/SMTP/Send_Text/Send_Text.ino#L209-L221

**Comment by mobizt** [comment]
The device time should be valid by manually set or sync with NTP server or RTC chip or library internal NTP server synching.

This valid time is required for creating `Date` header of message to avoid the receiver considered your message as spam.

**Comment by marmou-fritzing** [comment]
I understand. Thank You. I try set it manually immediatelly after start of device with helpful of smtp.setSystemTime(WiFi.getTime());. I report result.

**Comment by mobizt** [comment]
Do you know what is WiFiNINA?

WiFiNINA is the WiFi library and firmware for SMD21 and RPI2040 devices with U-block ESP32 based WiFi module built-in, not for ESP32 based boards.

For ESP32 and ESP8266, there are many resources about NTP time in youtube and google search. It is simple and easy by just call

`configTime(gmtOffsetInSeconds, daylightOffsetInSeconds, "pool.ntp.org", "time.nist.gov");`

Then you need to wait the value returns from function `time(nullptr)` to be valid timestampt (uint32_t or tiime_t).

I assume that you understand what is timestamp, if not search google.

**Comment by mobizt** [comment]
https://github.com/mobizt/ESP-Mail-Client#samd21

**Comment by marmou-fritzing** [comment]
Yes, I understand and I don't wanted use WIFININA. :-) I only reported, that function getTime() for ESP32 not found and You confirmed me, that is neccssary use any other method.
Thank you and have a nice day!
