### ISSUE TITLE
tcp_client_base.h:166:24: error: variable 'TCP_Client_Base::setTimestamp(time_t)::timeval tm' has initializer but incomplete type

### ISSUE THREAD

**Issue by fsnuffer** [mobizt/ESP-Mail-Client#193]
If I downgrade library the sketch compiles.  Experiance same compile error on multiple machins.

Arduino: 1.8.19 (Windows Server 2016), Board: "ESP32 Dev Module, Disabled, Default 4MB with spiffs (1.2MB APP/1.5MB SPIFFS), 240MHz (WiFi/BT), QIO, 80MHz, 4MB (32Mb), 921600, None"

In file included from C:\Users\Administrator\Documents\Arduino\libraries\ESP_Mail_Client\src\wcs\esp32\ESP32_SSL_Client.h:40:0,

                 from C:\Users\Administrator\Documents\Arduino\libraries\ESP_Mail_Client\src\wcs\esp32\ESP32_SSL_Client.cpp:44:

c:\users\administrator\documents\arduino\libraries\esp_mail_client\src\wcs\base\tcp_client_base.h: In member function 'int TCP_Client_Base::setTimestamp(time_t)':

c:\users\administrator\documents\arduino\libraries\esp_mail_client\src\wcs\base\tcp_client_base.h:166:24: error: variable 'TCP_Client_Base::setTimestamp(time_t)::timeval tm' has initializer but incomplete type

         struct timeval tm = {ts, 0}; // sec, us

                        ^

c:\users\administrator\documents\arduino\libraries\esp_mail_client\src\wcs\base\tcp_client_base.h:167:52: error: 'settimeofday' was not declared in this scope

         return settimeofday((const timeval *)&tm, 0);

                                                    ^

In file included from C:\Users\Administrator\Documents\Arduino\libraries\ESP_Mail_Client\src\wcs\esp32\ESP32_SSL_Client.h:40:0,

                 from C:\Users\Administrator\Documents\Arduino\libraries\ESP_Mail_Client\src\wcs\esp32\ESP32_WCS.h:57,

                 from C:\Users\Administrator\Documents\Arduino\libraries\ESP_Mail_Client\src\wcs\esp32\ESP32_WCS.cpp:54:

c:\users\administrator\documents\arduino\libraries\esp_mail_client\src\wcs\base\tcp_client_base.h: In member function 'int TCP_Client_Base::setTimestamp(time_t)':

c:\users\administrator\documents\arduino\libraries\esp_mail_client\src\wcs\base\tcp_client_base.h:166:24: error: variable 'TCP_Client_Base::setTimestamp(time_t)::timeval tm' has initializer but incomplete type

         struct timeval tm = {ts, 0}; // sec, us

                        ^

c:\users\administrator\documents\arduino\libraries\esp_mail_client\src\wcs\base\tcp_client_base.h:167:52: error: 'settimeofday' was not declared in this scope

         return settimeofday((const timeval *)&tm, 0);

                                                    ^

Multiple libraries were found for "SD.h"

 Used: C:\Users\Administrator\AppData\Local\Arduino15\packages\esp32\hardware\esp32\1.0.6\libraries\SD

 Not used: D:\Program Files (x86)\Arduino\libraries\SD

Multiple libraries were found for "WiFi.h"

 Used: C:\Users\Administrator\AppData\Local\Arduino15\packages\esp32\hardware\esp32\1.0.6\libraries\WiFi

 Not used: D:\Program Files (x86)\Arduino\libraries\WiFi

exit status 1

Error compiling for board ESP32 Dev Module.

This report would have more information with
"Show verbose output during compilation"
option enabled in File -> Preferences.

**Comment by mobizt** [comment]
Thanks for reporting this issue.

The library [v2.5.1](https://github.com/mobizt/ESP-Mail-Client/releases/tag/v2.5.1) is available with this issue fixed, please update.
