### ISSUE TITLE
LittleFS Failed

### ISSUE THREAD

**Issue by hall1235** [mobizt/ESP-Mail-Client#197]
Hello mobizt

I have a problem with initial spiffs fails.
I use spiffs to storage the server files

Window 10
Arduino IDE Version 1.8.19
Board :  ESP32 Dev module
Board Manager version Esp32 : 2.0.5
Partition scheme : NO OTA 2MB APP/2MB SPIFFS

This is my simple code

  email_sdcard = SdEmail.sdBegin( sd_cs, &spiSD, sd_freq );
  Serial.println( email_sdcard ? "Initial SD Success" : "Initial SD Fail." );
  while ( WiFi.status() != WL_CONNECTED ) delay( 500 );

  session.server.host_name  = smtp_host.c_str();
  session.server.port       = smtp_port;
  session.login.email       = smtp_sender_user.c_str();
  session.login.password    = smtp_sender_pass.c_str();
  session.login.user_domain = F("");
  message.sender.email      = smtp_sender_user.c_str();

  session.time.ntp_server = F("pool.ntp.org,time.nist.gov");
  session.time.gmt_offset = 7;
  session.time.day_light_offset = 0;

  message.addRecipient("staff", smtp_receiver_email.c_str() );
  message.sender.name = F("FM150W");
  message.subject = model_name.c_str();

  SMTP_Attachment att;
  att.descr.filename = F("dataloger_20220422.csv");
  att.descr.mime = F("application/octet-stream");
  att.file.path = F("/d_20220928.csv");
  att.file.storage_type = esp_mail_file_storage_type_sd;
  att.descr.transfer_encoding = Content_Transfer_Encoding::enc_base64;

  message.addAttachment(att);
  if (!smtp.connect(&session))
    return;
  MailClient.sendMail(&smtp, &message, true);
 
This is my Error Show on Serial Monitor
./components/esp_littlefs/src/littlefs/lfs.c:1229:error: Corrupted dir pair at {0x0, 0x1}
E (2064) esp_littlefs: mount failed,  (-84)
E (2065) esp_littlefs: Failed to initialize LittleFS

Thank your so much

**Comment by mobizt** [comment]
Do you understand the different between SD and Flash filesystems?

You can search google for this.

Follow the examples and read all comments that described all information that you should know before adapt it.
