### ISSUE TITLE
Fetch messages

### ISSUE THREAD

**Issue by joerg2909** [mobizt/ESP-Mail-Client#23]
Hi 
I got the error
Fetching message 1, UID: 100
> C: send imap command, FETCH
> C: fetch message header
$ UID FETCH 100 BODY.PEEK[HEADER.FIELDS (SUBJECT FROM TO DATE CC Message-ID Accept-Language content-type Content-transfer-encoding Content-Language)]
$ OK Success
Error, some of the requested messages no longer exist
> E: some of the requested messages no longer exist

Can you help me?
Thanks
Juergen

**Comment by mobizt** [comment]
The UID 100 is for example which you need to provide the UID of your message to read.

You never know the UID of message in the mailbox unless you search it.

Please check [this example](https://github.com/mobizt/ESP-Mail-Client/blob/master/examples/Search_Emails/Search_Emails.ino) which you will get the UID to read the message later.
