### ISSUE TITLE
Doesn't compile

### ISSUE THREAD

**Issue by workpage2** [mobizt/ESP-Mail-Client#235]
### Discussed in https://github.com/mobizt/ESP-Mail-Client/discussions/234

<div type='discussions-op-text'>

<sup>Originally posted by **workpage2** March  3, 2023</sup>
Library version 3.0.1
If you disable the `#define ENABLE_IMAP` line in the ESP_Mail FS file, the sketch stops compiling.</div>

**Comment by mobizt** [comment]
I already know it and do not need to open the issue.

**Comment by mobizt** [comment]
The library updated with issues fixed. Please update.
