### ISSUE TITLE
SMTP does not authenticate.

### ISSUE THREAD

**Issue by Plashu** [mobizt/ESP-Mail-Client#244]
**Build tool used:**

- [ ] Arudino
- [x] Platformio (Visual Studio Code plugin)
- [ ] Platformio CLI
- [ ] Other

**Board used (ESP32/ESP8266/Arudino):**

- [ ] ESP8266-based
- [x] ESP32-based

**Other Libraries That are used:**

Changes in ESP_Mail_SMTP.h from commit# c6f7ca3 break SMTP authentication.

> C: ESP Mail Client v3.1.0
> C: connecting to SMTP server
> C: Host > smtp.gmail.com
> C: Port > 465

> C: SSL/TLS negotiation
> C: seeding the random number generator
> C: setting up the SSL/TLS structure
> C: loading CA cert
> C: setting hostname for TLS session
> C: perform the SSL/TLS handshake
> C: verifying peer X.509 certificate

> C: SMTP server connected, wait for greeting...
< S: 220 smtp.gmail.com ESMTP x18-[REDACTED].52 - gsmtp

> C: send SMTP command, HELO
< S: 250-smtp.gmail.com at your service, [REDACTED]
< S: 250-SIZE 35882577
< S: 250-8BITMIME
< S: 250-AUTH LOGIN PLAIN XOAUTH2 PLAIN-CLIENTTOKEN OAUTHBEARER XOAUTH
< S: 250-ENHANCEDSTATUSCODES
< S: 250-PIPELINING
< S: 250-CHUNKING
< S: 250 SMTPUTF8

> C: send Email

> C: send message header
< S: 530-5.7.0 Authentication Required. Learn more at
< S: 530 5.7.0  https://support.google.com/mail/?p=WantAuthError x18-[REDACTED].52 - gsmtp
! E: send header failed
> C: cleaning SSL connection
Error sending email: send header failed

After reverting changes for that file in parseAuthCapability() function:

> C: ESP Mail Client v3.1.0
> C: connecting to SMTP server
> C: Host > smtp.gmail.com
> C: Port > 465

> C: SSL/TLS negotiation
> C: seeding the random number generator
> C: setting up the SSL/TLS structure
> C: loading CA cert
> C: setting hostname for TLS session
> C: perform the SSL/TLS handshake
> C: verifying peer X.509 certificate

> C: SMTP server connected, wait for greeting...
< S: 220 smtp.gmail.com ESMTP k23-[REDACTED].154 - gsmtp

> C: send SMTP command, HELO
< S: 250-smtp.gmail.com at your service, [REDACTED]
< S: 250-SIZE 35882577
< S: 250-8BITMIME
< S: 250-AUTH LOGIN PLAIN XOAUTH2 PLAIN-CLIENTTOKEN OAUTHBEARER XOAUTH
< S: 250-ENHANCEDSTATUSCODES
< S: 250-PIPELINING
< S: 250-CHUNKING
< S: 250 SMTPUTF8
> C: send SMTP command, AUTH PLAIN
> C: [REDACTED]@gmail.com
> C: ****************
< S: 235 2.7.0 Accepted

> C: send Email

> C: send message header
< S: 250 2.1.0 OK k23-[REDACTED].154 - gsmtp
< S: 250 2.1.5 OK k23-[REDACTED].154 - gsmtp

> C: send message body
< S: 354  Go ahead k23-[REDACTED].154 - gsmtp

> C: finishing the message sending
< S: 250 2.0.0 OK  1678924199 k23-[REDACTED].154 - gsmtp
Email Sent
> C: listening to Test folder changes
> C: polling established on Wed, 15 Mar 2023 19:50:00 -0400
IMAP listen

> C: terminate the SMTP session

> C: message sent successfully
> C: cleaning SSL connection

**Comment by mobizt** [comment]
Thanks for reporting this issue. I will check and update soon.

**Comment by mobizt** [comment]
Now the library [ v3.1.1](https://github.com/mobizt/ESP-Mail-Client/releases/tag/v3.1.1) is available, please update.
