### ISSUE TITLE
Undefined variable when storage is not defined

### ISSUE THREAD

**Issue by Plashu** [mobizt/ESP-Mail-Client#253]
I believe it should be set to mb_fs_mem_storage_type type = mb_fs_mem_storage_type_undefined;

P.S. I don't know how to to pull requests so I am just telling you this way, there are some additional more minor issues/improvements I have found but don't know the best way to address them.

https://github.com/mobizt/ESP-Mail-Client/blob/c17149e05ce05e36631ad2e3011850b7636beea8/src/ESP_Mail_Client.cpp#L488
https://github.com/mobizt/ESP-Mail-Client/blob/c17149e05ce05e36631ad2e3011850b7636beea8/src/ESP_Mail_Client.cpp#L591

**Comment by mobizt** [comment]
Actually it's default enum value of that var (type) is 0 or `mb_fs_mem_storage_type_undefined` 

No problem I will change as you suggested.
