### ISSUE TITLE
SD_MMC not attaching file to email

### ISSUE THREAD

**Issue by wiehen** [mobizt/ESP-Mail-Client#261]
**Build tool used:**

- [X] Arudino
- [ ] Platformio (Visual Studio Code plugin)
- [ ] Platformio CLI
- [ ] Other

**Board used (ESP32/ESP8266/Arudino):**

- [ ] ESP8266-based
- [X] ESP32-based

**Other Libraries That are used:**

#include "esp_camera.h"
#include "Arduino.h"
#include "FS.h"                // SD Card ESP32
#include "SD_MMC.h"            // SD Card ESP32
#include "soc/soc.h"           
#include "soc/rtc_cntl_reg.h"  
#include <EEPROM.h>            // read and write from flash memory
#include <WiFi.h>

**Description of problem:**
I am using SD_MMC to write a picture that is taken to the sd card. This is done successfully and I can see the picture on the card if I look at it. I cannot get the mail client to attach the picture to the email using SD_MMC. The email is sent successfully and received just with no attachment.

It does not seem like these definitions in my code
define ESP_MAIL_DEFAULT_SD_FS SD_MMC //For ESP32 SDMMC
#define ESP_MAIL_CARD_TYPE_SD_MMC 1
do anything when you include SDHelper.h it never reaches the if statement that is defined by the above. It always goes to the section defined like this:

#elif defined(ESP32) // if ESP32 and no SdFat library installed
    Serial.print("\nMounting SD Card... No SDFat... ");

You can see that I changed the serial.print statement in my code and you can see the matching output in my serial output below.

**Share code snippet to reproduce the issue:**

PASTE .cpp / .ino code here

```
#include <ESP_Mail_Client.h>

#include "esp_camera.h"
#include "Arduino.h"
#include "FS.h"                // SD Card ESP32
#include "SD_MMC.h"            // SD Card ESP32
#include "soc/soc.h"           
#include "soc/rtc_cntl_reg.h"  
#include <EEPROM.h>            // read and write from flash memory
#include <WiFi.h>

#include <extras/SDHelper.h>

// define the number of bytes you want to access
#define EEPROM_SIZE 1

// Pin definition for CAMERA_MODEL_AI_THINKER
#define PWDN_GPIO_NUM     32
#define RESET_GPIO_NUM    -1
#define XCLK_GPIO_NUM      0
#define SIOD_GPIO_NUM     26
#define SIOC_GPIO_NUM     27

#define Y9_GPIO_NUM       35
#define Y8_GPIO_NUM       34
#define Y7_GPIO_NUM       39
#define Y6_GPIO_NUM       36
#define Y5_GPIO_NUM       21
#define Y4_GPIO_NUM       19
#define Y3_GPIO_NUM       18
#define Y2_GPIO_NUM        5
#define VSYNC_GPIO_NUM    25
#define HREF_GPIO_NUM     23
#define PCLK_GPIO_NUM     22

#define ESP_MAIL_DEFAULT_SD_FS SD_MMC //For ESP32 SDMMC
#define ESP_MAIL_CARD_TYPE_SD_MMC 1

int pictureNumber = 0;
camera_fb_t * fb = NULL; // pointer
const char* ssid     = "Nathanwifi";
const char* password = "9192644667";
int value = 0;
// Declare the global used SMTPSession object for SMTP transport
SMTPSession smtp;

// Declare the global used Session_Config for user defined session credentials
Session_Config mailConfig;

WiFiServer server(80);

void setup() {
  WRITE_PERI_REG(RTC_CNTL_BROWN_OUT_REG, 0); 
 
  Serial.begin(115200);
  Serial.setDebugOutput(true);
  Serial.println();
  Serial.print("MOSI: ");
  Serial.println(MOSI);
  Serial.print("MISO: ");
  Serial.println(MISO);
  Serial.print("SCK: ");
  Serial.println(SCK);
  Serial.print("SS: ");
  Serial.println(SS);  

  delay(10);

  // We start by connecting to a WiFi network
  Serial.println();
  Serial.println();
  Serial.print("Connecting to ");
  Serial.println(ssid);

  WiFi.begin(ssid, password);

  while (WiFi.status() != WL_CONNECTED) {
      delay(500);
      Serial.print(".");
  }

  Serial.println("");
  Serial.println("WiFi connected.");
  Serial.println("IP address: ");
  Serial.println(WiFi.localIP());
  
  server.begin();

  camera_config_t config;
  config.ledc_channel = LEDC_CHANNEL_0;
  config.ledc_timer = LEDC_TIMER_0;
  config.pin_d0 = Y2_GPIO_NUM;
  config.pin_d1 = Y3_GPIO_NUM;
  config.pin_d2 = Y4_GPIO_NUM;
  config.pin_d3 = Y5_GPIO_NUM;
  config.pin_d4 = Y6_GPIO_NUM;
  config.pin_d5 = Y7_GPIO_NUM;
  config.pin_d6 = Y8_GPIO_NUM;
  config.pin_d7 = Y9_GPIO_NUM;
  config.pin_xclk = XCLK_GPIO_NUM;
  config.pin_pclk = PCLK_GPIO_NUM;
  config.pin_vsync = VSYNC_GPIO_NUM;
  config.pin_href = HREF_GPIO_NUM;
  config.pin_sscb_sda = SIOD_GPIO_NUM;
  config.pin_sscb_scl = SIOC_GPIO_NUM;
  config.pin_pwdn = PWDN_GPIO_NUM;
  config.pin_reset = RESET_GPIO_NUM;
  config.xclk_freq_hz = 20000000;
  config.pixel_format = PIXFORMAT_JPEG; 

config.frame_size = FRAMESIZE_SVGA;
    config.jpeg_quality = 12;
    config.fb_count = 2;

  esp_err_t err = esp_camera_init(&config);
  if (err != ESP_OK) {
    Serial.printf("Camera init failed with error 0x%x", err);
    return;
  }

  // Take a photo with the camera
  Serial.println();
  Serial.println("Taking a photo...");

  //Serial.println("Starting SD Card");
  if(!SD_MMC.begin()){
    Serial.println("SD Card Mount Failed");
    return;
  }
  
  uint8_t cardType = SD_MMC.cardType();
  if(cardType == CARD_NONE){
    Serial.println("No SD Card attached");
    return;
  }

  // Take Picture with Camera
  fb = esp_camera_fb_get();  
  if(!fb) {
    Serial.println("Camera capture failed");
    return;
  }
  // initialize EEPROM with predefined size
  EEPROM.begin(EEPROM_SIZE);
  pictureNumber = EEPROM.read(0) + 1;

  // Path where new picture will be saved in SD Card
  String name = "picture" + String(pictureNumber) + ".jpg";
  String path = "/picture" + String(pictureNumber) +".jpg";

  fs::FS &fs = SD_MMC; 
  Serial.printf("Picture file name: %s\n", path.c_str());
  
  File file = fs.open(path.c_str(), FILE_WRITE);
  if(!file){
    Serial.println("Failed to open file in writing mode");
  } 
  else {
    file.write(fb->buf, fb->len); // payload (image), payload length
    Serial.printf("Saved file to path: %s\n", path.c_str());
    EEPROM.write(0, pictureNumber);
    EEPROM.commit();
  }
  file.close();
  esp_camera_fb_return(fb);

  mailConfig.server.host_name = "smtp.gmail.com"; // for outlook.com
  mailConfig.server.port = 587; // for TLS with STARTTLS or 25 (Plain/TLS with STARTTLS) or 465 (SSL)
  mailConfig.login.email = "wiehen1@gmail.com"; // set to empty for no SMTP Authentication
  mailConfig.login.password = "bpkttmhlgowfvqmd"; // set to empty for no SMTP Authentication

  mailConfig.time.ntp_server = "pool.ntp.org,time.nist.gov";
  mailConfig.time.gmt_offset = 3;
  mailConfig.time.day_light_offset = 0;

  // Declare the SMTP_Message class variable to handle to message being transport
  SMTP_Message message;

  // Set the message headers
  message.sender.name = "ESP32";
  message.sender.email = "wiehen1@gmail.com";
  message.subject = "Test sending Email";
  message.addRecipient("Nathan Wiehe", "wiehen@yahoo.com");

  message.enable.chunking = true;
  message.html.charSet = "utf-8";
  message.html.content = "<span style=\"color:#ff0000;\">Camera image attached</span><br/><br/>";

  message.priority = esp_mail_smtp_priority::esp_mail_smtp_priority_low;

  SD_Card_Mounting();
   /* The attachment data item */
  SMTP_Attachment att;

  /** Set the attachment info e.g. 
   * file name, MIME type, file path, file storage type,
   * transfer encoding and content encoding
  */
  att.descr.filename = name;
  att.descr.mime = "image/jpg";
  att.file.path = path;
  att.file.storage_type = esp_mail_file_storage_type_sd;
  att.descr.transfer_encoding = Content_Transfer_Encoding::enc_base64;

  /* Add attachment to the message */
  message.addAttachment(att);
 
  /* Connect to server with the session config */
  if (!smtp.connect(&mailConfig)) {
    ESP_MAIL_PRINTF("Connection error, Status Code: %d, Error Code: %d, Reason: %s", smtp.statusCode(), smtp.errorCode(), smtp.errorReason().c_str());
    return;
  }

   /* Start sending the Email and close the session */
  if (!MailClient.sendMail(&smtp, &message, true)) {
    Serial.println("Error sending Email, " + smtp.errorReason());
  }
}

void loop() {

}
```
**Additional information and things you've tried:**
Here is my Serial Monitor output

-----------------
MOSI: 23
MISO: 19
SCK: 18
SS: 5

Connecting to Nathanwifi
[   533][D][WiFiGeneric.cpp:1035] _eventCallback(): Arduino Event: 0 - WIFI_READY
[   621][D][WiFiGeneric.cpp:1035] _eventCallback(): Arduino Event: 2 - STA_START
.........[  5552][D][WiFiGeneric.cpp:1035] _eventCallback(): Arduino Event: 5 - STA_DISCONNECTED
[  5552][W][WiFiGeneric.cpp:1057] _eventCallback(): Reason: 2 - AUTH_EXPIRE
[  5555][D][WiFiGeneric.cpp:1077] _eventCallback(): WiFi Reconnect Running
...[  7076][D][WiFiGeneric.cpp:1035] _eventCallback(): Arduino Event: 4 - STA_CONNECTED
.[  7610][D][WiFiGeneric.cpp:1035] _eventCallback(): Arduino Event: 7 - STA_GOT_IP
[  7611][D][WiFiGeneric.cpp:1098] _eventCallback(): STA IP: 10.0.0.60, MASK: 255.255.255.0, GW: 10.0.0.1
.
WiFi connected.
IP address: 
10.0.0.60

Taking a photo...
Picture file name: /picture92.jpg
Saved file to path: /picture92.jpg

Mounting SD Card... No SDFat... [  8104][W][sd_diskio.cpp:516] ff_sd_initialize(): GO_IDLE_STATE failed
[  8105][E][sd_diskio.cpp:802] sdcard_mount(): f_mount failed: (3) The physical drive cannot work
failed

[ 11206][W][sd_diskio.cpp:516] ff_sd_initialize(): GO_IDLE_STATE failed
[ 11206][E][sd_diskio.cpp:802] sdcard_mount(): f_mount failed: (3) The physical drive cannot work
[ 11451][I][ESP32_SSL_Client.cpp:244] connect_ssl(): WARNING: Skipping SSL Verification. INSECURE!
[ 13802][W][sd_diskio.cpp:180] sdCommand(): crc error
[ 13902][W][sd_diskio.cpp:516] ff_sd_initialize(): GO_IDLE_STATE failed
[ 13903][E][sd_diskio.cpp:802] sdcard_mount(): f_mount failed: (3) The physical drive cannot work
[ 13907][W][sd_diskio.cpp:186] sdCommand(): token error [0] 0x41
[ 14855][D][WiFiClient.cpp:546] connected(): Disconnected: RES: 0, ERR: 128
--------------------

I have changed SDHelper.h top match my SPI settings:
#if defined(ESP32)

//#define SPI_CS_PIN 13
//#define SPI_SCK_PIN 14
//#define SPI_MISO_PIN 2
//#define SPI_MOSI_PIN 15
//#define SPI_CLOCK_IN_MHz 16

 #define SPI_CS_PIN 5
 #define SPI_SCK_PIN 18
 #define SPI_MISO_PIN 19
 #define SPI_MOSI_PIN 23
 #define SPI_CLOCK_IN_MHz 4 // may work on lower clock rate

I try calling SD_Card_Mounting() in my code to see if that will work you can see from the output that it also fails to mount the card.

**Comment by mobizt** [comment]
Please read the comments in the examples carefully.

Why you define this in your sketch? Where is the document you've seen that show you to do this.

```cpp
#define ESP_MAIL_DEFAULT_SD_FS SD_MMC //For ESP32 SDMMC
#define ESP_MAIL_CARD_TYPE_SD_MMC 1
```
That causes library can't see those maros you defined in your sketch and it will cause macro re-definition conflicts when compiling your sketch.


Only the place where you can define those maros is [ESP_Mail_FS.h](https://github.com/mobizt/ESP-Mail-Client/blob/master/src/ESP_Mail_FS.h#L117-L118)
https://github.com/mobizt/ESP-Mail-Client/blob/21962ab69ab583abe54bc286d9b1b3fe56536ceb/src/ESP_Mail_FS.h#L117-L118

The [ESP_Mail_FS.h](https://github.com/mobizt/ESP-Mail-Client/blob/master/src/ESP_Mail_FS.h) contains the default library configurations which your can create your own configuration file (Custom_ESP_Mail_FS.h) where it does not overwrite when you update the library which already stated in that file.

https://github.com/mobizt/ESP-Mail-Client/blob/21962ab69ab583abe54bc286d9b1b3fe56536ceb/src/ESP_Mail_FS.h#L159-L190
 
Also, you should remove your following card initialization code from your sketch
` if(!SD_MMC.begin()){`
And use library provided card initialization function instead.
` SD_Card_Mounting();`

If you intend to save your image to storage card before sending email, and you don't use multimedia card (mmc) unless use only SD or micro-SD card, please use SD library or high-performance library [SdFat](https://github.com/greiman/SdFat) instead.

If you only want to send raw image, please follow [this example](https://github.com/mobizt/ESP-Mail-Client/blob/master/examples/SMTP/Send_Camera_Image/ESP_Camera/ESP_Camera.ino).

**Comment by wiehen** [comment]
I added the custom Custom_ESP_Mail_FS.h file with the SD_MMC override like is documented. When I compile my program after removing these statements from my ino file:
//#define ESP_MAIL_DEFAULT_SD_FS SD_MMC //For ESP32 SDMMC
//#define ESP_MAIL_CARD_TYPE_SD_MMC 1

I now get this error message:

In file included from /Users/nathanwiehe/Documents/Arduino/libraries/ESP-Mail-Client/src/extras/RFC2047.h:13,
                 from /Users/nathanwiehe/Documents/Arduino/libraries/ESP-Mail-Client/src/ESP_Mail_Client.h:39,
                 from /Users/nathanwiehe/Documents/Arduino/camera_mail_attachment/camera_mail_attachment.ino:1:
/Users/nathanwiehe/Documents/Arduino/libraries/ESP-Mail-Client/src/extras/MB_FS.h: In member function 'bool MB_FS::sdSPIBegin(int, SPIClass*, uint32_t)':
/Users/nathanwiehe/Documents/Arduino/libraries/ESP-Mail-Client/src/extras/MB_FS.h:256:74: error: no matching function for call to 'fs::SDMMCFS::begin(int&, SPIClass&, uint32_t&)'
             sd_rdy = MBFS_SD_FS.begin(ss, *sd_config.spiConfig, frequency);
                                                                          ^
In file included from /Users/nathanwiehe/Documents/Arduino/libraries/ESP-Mail-Client/src/Custom_ESP_Mail_FS.h:17,
                 from /Users/nathanwiehe/Documents/Arduino/libraries/ESP-Mail-Client/src/ESP_Mail_FS.h:194,
                 from /Users/nathanwiehe/Documents/Arduino/libraries/ESP-Mail-Client/src/extras/RFC2047.h:12,
                 from /Users/nathanwiehe/Documents/Arduino/libraries/ESP-Mail-Client/src/ESP_Mail_Client.h:39,
                 from /Users/nathanwiehe/Documents/Arduino/camera_mail_attachment/camera_mail_attachment.ino:1:
/Users/nathanwiehe/Library/Arduino15/packages/esp32/hardware/esp32/2.0.9/libraries/SD_MMC/src/SD_MMC.h:53:10: note: candidate: 'bool fs::SDMMCFS::begin(const char*, bool, bool, int, uint8_t)'
     bool begin(const char * mountpoint="/sdcard", bool mode1bit=false, bool format_if_mount_failed=false, int sdmmc_frequency=BOARD_MAX_SDMMC_FREQ, uint8_t maxOpenFiles = 5);
          ^~~~~
/Users/nathanwiehe/Library/Arduino15/packages/esp32/hardware/esp32/2.0.9/libraries/SD_MMC/src/SD_MMC.h:53:10: note:   no known conversion for argument 2 from 'SPIClass' to 'bool'
Multiple libraries were found for "SD.h"
  Used: /Users/nathanwiehe/Library/Arduino15/packages/esp32/hardware/esp32/2.0.9/libraries/SD
  Not used: /Users/nathanwiehe/Library/Arduino15/libraries/SD
exit status 1

Compilation error: exit status 1

**Comment by mobizt** [comment]
Fist, remove your `Custom_ESP_Mail_FS.h` and modify the `ESP_Mail_FS.h` with SD_MMC to make sure you do the right thing.

If everything is ok with modified ESP_Mail_FS.h then implement the `Custom_ESP_Mail_FS.h`.

Consult the C/C++ programming documentation for programming.

**Comment by mobizt** [comment]
### As I mentioned already, you should use SD.h library and SdFat library instead of SD_MMC.
