### ISSUE TITLE
Example fails to compile: "config" variable declared twice

### ISSUE THREAD

**Issue by PPoliakoff** [mobizt/ESP-Mail-Client#280]
**Build tool used:**

- [X ] Arudino
- [ ] Platformio (Visual Studio Code plugin)
- [ ] Platformio CLI
- [ ] Other

**Board used (ESP32):**

- [ ] ESP8266-based
- [ X] ESP32-based

**Other Libraries That are used:**

**Description of problem:**
in the code of examples/SMTP/Send_Camera_Image/ESP_Camera/ESP_Camera.ino
The variable "config" is defined twice:

    camera_config_t config;
    Session_Config config;

This cause a compile error. 

**Share code snippet to reproduce the issue:**
```yaml
PASTE .cpp / .ino code here

```

**Additional information and things you've tried:**

**Comment by mobizt** [comment]
Thanks for reporting this. I will fix and update.

**Comment by mobizt** [comment]
Now it fixed already.
https://github.com/mobizt/ESP-Mail-Client/tree/master/examples/SMTP/Send_Camera_Image/ESP_Camera
