### ISSUE TITLE
Missing file in v3.4.5 (platformio)

### ISSUE THREAD

**Issue by gsicilia82** [mobizt/ESP-Mail-Client#296]
Hi, with latest version, the file "ESP_MAIL_TCPClient.h" is missing in PlatformIO package. Please, can you check your source code?

![image](https://github.com/mobizt/ESP-Mail-Client/assets/62556925/b086c230-5220-4b5d-bbab-6ae08f50ee98)

**Comment by 77pixel** [comment]
I took the file from ver 3.4.0, changed the version check as follow (inside the file) VALID_VERSION_CHECK(30405). Now its work.

**Comment by mobizt** [comment]
@gsicilia82 @77pixel 

Thanks for reporting this issue.

I fixed it already and publish the new version, v3.4.6.

Please update.
