### ISSUE TITLE
Change Debug Port - ESP_MAIL_DEBUG_PORT

### ISSUE THREAD

**Issue by allacmc** [mobizt/ESP-Mail-Client#315]
I'm using the Arduino IDE with this library and everything works perfectly. I'm very grateful, but I have a specific need: I need to have more detailed debug information in a serial file.

I have made these statements and none replace Serial:

      File oFileMail;
      #define ESP_MAIL_DEBUG_PORT oFileMail
      #define ESP_MAIL_DEFAULT_DEBUG_PORT oFileMail
      #include <ESP_Mail_Client.h>

I try:

      File oFileMail;
      //#define ESP_MAIL_DEBUG_PORT oFileMail
      #define ESP_MAIL_DEFAULT_DEBUG_PORT oFileMail
      #include <ESP_Mail_Client.h>

and try:

      File oFileMail;
      //#define ESP_MAIL_DEBUG_PORT oFileMail
      #define ESP_MAIL_DEFAULT_DEBUG_PORT oFileMail
      #include <ESP_Mail_Client.h>

What am I doing wrong ?

Is not work

**Comment by mobizt** [comment]
You can assign it in this file.
https://github.com/mobizt/ESP-Mail-Client/blob/d0e5bfec2d23fa6077d9b53b24b924a27e361d1f/src/ESP_Mail_FS.h#L169-L170
