### ISSUE TITLE
erosion of free heap

### ISSUE THREAD

**Issue by galed3e3** [mobizt/ESP-Mail-Client#32]
With:
Arduino IDE v1.8.13
ESP core v1.0.5
ESP-Mail-Client v1.0.13
Adafruit ESP32 Feather

Using code from example Send_text.ino

There is a drop in free heap with every email and slow erosion of free heap associated with email use, as shown in the attached image.

![slowHeapErosion](https://user-images.githubusercontent.com/8498663/109610276-04aef980-7ad9-11eb-94a2-58e7dd0627cd.jpg)

**Comment by mobizt** [comment]
All the data passed to the function by pointer.
No memory leak inside the library unless the user code.

**Comment by mobizt** [comment]
This is normal as the memory used by the system tasks and core libraries too.
