### ISSUE TITLE
received email with base64 when i use the smtp server from (189.cn 139.com qq.com)

### ISSUE THREAD

**Issue by yunhai20082008** [mobizt/ESP-Mail-Client#321]
Arudino esp32
`
    String subject = stage + String("+") + sendStr;
    String sender_name = "Me";
    String textMsg = subject;
    
    void smtpCallback(SMTP_Status status);
    MailClient.networkReconnect(true);
    
    smtp.debug(1);
    smtp.callback(smtpCallback);
    Session_Config config;
    config.server.host_name = SMTP_HOST;
    config.server.port = SMTP_PORT;
    config.login.email = AUTHOR_EMAIL;
    config.login.password = AUTHOR_PASSWORD; 
    config.login.user_domain = F("127.0.0.1");
    config.time.ntp_server = F("pool.ntp.org,time.nist.gov");
    config.time.gmt_offset = 3;
    config.time.day_light_offset = 0;
    
    SMTP_Message message; 
    message.sender.name = sender_name;
    message.sender.email = AUTHOR_EMAIL;
    message.subject = subject;
    message.addRecipient(F("Someone"), RECIPIENT_EMAIL);
    message.text.content = textMsg;
    message.text.transfer_encoding = "base64"; // recommend for non-ASCII words in message.
    message.text.charSet = F("utf-8"); // recommend for non-ASCII words in message.
    message.priority = esp_mail_smtp_priority::esp_mail_smtp_priority_low;
    message.addHeader(F(AUTHOR_EMAIL));

    SMTP_Attachment att[1];
    int attIndex = 0;
    att[attIndex].descr.filename = F("data.7z");
    att[attIndex].descr.mime = F("application/octet-stream"); // binary data
    att[attIndex].descr.description = F("data");
    att[attIndex].file.path = F("/data.7z");
    att[attIndex].file.storage_type = esp_mail_file_storage_type_flash;
    att[attIndex].descr.transfer_encoding = Content_Transfer_Encoding::enc_base64;
    message.addAttachment(att[attIndex]);
`
when I set the sender email from the smtp of (qq,189,139).the email reveived style is base64-content like below
`
[1289xxxx@qq.com](mailto:12xxxxx@qq.com)
Date: Thu, 29 Feb 2024 08:30:26 +0800
Mime-Version: 1.0
Content-Type: multipart/mixed; boundary="=_jhSDb5FKG9Q4";

--=_jhSDb5FKG9Q4
Content-Type: text/plain; charset="utf-8";
Content-transfer-encoding: base64

c3RhZ2UzKzdDOjlFOkJEOkUyOkY3OjVDKzE=

--=_jhSDb5FKG9Q4
Content-Type: application/octet-stream; Name="data.7z";
Content-Disposition: attachment; filename="data.7z"; size=935;
Content-transfer-encoding: base64
Content-Description: data

QQMail-LinkID:ZF0029_7u7NplyMEPEuKWUAXOotYe2
QQMail-LinkSize:935
QQMail-LineLen:76
QQMail-BreakType:1
QQMail-Key:2e6a684b71fe642a7814fb5da3d0b963
QQMail-MD5:c5687f12071c2fe9cabe40cdfb604e77
QQMail-LinkEnd

--=_jhSDb5FKG9Q4--
`
when I set the sender email from the smtp of (163 and outlook).the email reveived style is normal with a string and a file

**Comment by mobizt** [comment]
It depends on this instead.
`message.text.transfer_encoding = "base64";`
