### ISSUE TITLE
ESP_Mail_Client is not always able to automatically recover from a WiFi signal lost

### ISSUE THREAD

**Issue by pberna67** [mobizt/ESP-Mail-Client#341]
Dear Mobizt,

I've encountered a problem using the library when the WiFi connection is lost due to a fading of the WiFi signal between the ESP32 module and the router. If the connection is lost, the library is no longer able to restore it again. The conditions for reproducing the problem are as follows: 

**Hw:** EVK-NINA-W101 based on  ESP32 
https://www.u-blox.com/en/product/evk-nina-w10
**Board lib package:**  ESP32 2.0.15 installed
**Sketch  example:** Mailbox_Change_Notification, the example provided by K. Suwatchai (Mobizt), just modified to provide every 10 seconds the result of the connection to the imap server as well as to the WiFi router (see attached sketch).
**ESP_Mail_Client:** 3.4.19 installed

Arduino Settings:

![image](https://github.com/mobizt/ESP-Mail-Client/assets/17097864/9fa06f76-5286-4f08-9577-e6dbd0919238)

**How to reproduce the problem:**
The app Mailbox_Change_Notification connects to internet via a router (in my case is a WiFi LTE router).  Move slowly the EVN-NINA-W102 (ESP32) board far from the router wifi range, until the ESP32 will lost the Wifi connection (**do not switch off the router and then switch on it, to simulate the Wifi drop, otherwise the problem doesn’t occurs**). Wait some minutes (5-7 minutes, see Serial.Dump, wait for that time or more, shorter time couldn't trigger the problem) with ESP32 position out of Wifi range of the router, then slowly enter the ESP 32 EVK in the range of the Wifi rounter. The result is that the sketch is not able to reconnect to the WiFi and so to the imap server again.
I have noticed that the connectWiFi()  callback is not invoked by the ESP-Mail-Client, to recover the situation
**Unfortunately is not easy to reproduce this situation, because it doesn't always occurs.**

[Mailbox_Changes_Notification_github.zip](https://github.com/mobizt/ESP-Mail-Client/files/15134886/Mailbox_Changes_Notification_github.zip)

[SerialDump.txt](https://github.com/mobizt/ESP-Mail-Client/files/15135191/SerialDump.txt)

Regards
Paolo

**Comment by mobizt** [comment]
The WiFiNINA does not allow the reconnection without the credential.

You have to add the WiFi credentials like this.
https://github.com/mobizt/ESP-Mail-Client/blob/78b8e7b4270199dab5f14265ad565acd80f10465/examples/IMAP/Mailbox_Changes_Notification/Mailbox_Changes_Notification.ino#L167-L168

**Comment by pberna67** [comment]
Dear mobizt

Ok, but in your code seems they are necessary only for

**Comment by mobizt** [comment]
No. any device that does not have reconnect feature except for ESP9266 and ESP32, should add the AP credentials.

**Comment by mobizt** [comment]
This feature is available many years ago.

**Comment by mobizt** [comment]
I focus on Raspbeery Pi Pico because it has enough memory for using IMAP as ESP32.

For your device, if you can program ESP32 directly, you don't have to add this AP credentials.

I think that you are using another MCU that using Ublox module which you can't access ESP32 directly.

**Comment by pberna67** [comment]
Dear mobizt].

I'm a bit confused, I mean  the solution to my problem is not to add, in the setup section of the code 

MailClient.clearAP();
MailClient.addAP(WIFI_SSID, WIFI_PASSWORD);

correct?
Regards
Paolo

**Comment by mobizt** [comment]
How do you reconnect the `WiFi` in your code without calling `WiFi.begin` again?

If you understand the objective of those functions, you will not ask me such a question.

**Comment by pberna67** [comment]
> I focus on Raspbeery Pi Pico because it has enough memory for using IMAP as ESP32.
> 
> For your device, if you can program ESP32 directly, you don't have to add this AP credentials.
> 
> I think that you are using another MCU that using Ublox module which you can't access ESP32 directly.

I'm using the NINA-W101 (I'm an u-blox employ), with integrated ESP32., I'm using directly the ESP32.
https://content.u-blox.com/sites/default/files/NINA-W10_DataSheet_UBX-17065507.pdf
I can send you an EVK (for free) if you need it for the analysys

Can you confirm the problem ?

I had similar problem in the past, I don't think is related to your lib, but to the way how the low level WiFi Arduino lib manages the WiFi interface, the key point is how to manage the recovery procedure in case of WiFi errors. I don't know how the Email Client lib recover the WiFi connection lost, however it seems that in case there are some cases in which the callback connectWiFi() is not invoked to reconnect the WiFi

Regards
Paolo

**Comment by mobizt** [comment]
You don't have to send me a device.  ESP32 is ESP32 with some variant.

The WiFi and network reconnection of library works normally for years as it was implemented in all my libraries.

It is just calling `WiFi.reconnect()` internally with proper timing to allow UDP to get the result.

The only issue is in WiFi core bugs in the outdated ESP32 Arduino core with  `WiFi.reconnect()`  which you have to update.

**Comment by pberna67** [comment]
Is WiFi.reconnect i in the

Board lib package: ESP32 2.0.15 installed  ?

Thanks

**Comment by mobizt** [comment]
I said clearly that in case outdated ESP32 Arduino core.

You have to try another ESP32 board instead of module and test.

This is quite issues of hardware failure, unstable power supply or PCB design.

**Comment by pberna67** [comment]
The problem is not hardware related because 3 different boards with 2 different cores have been tested, but it is somewhere in the ESP32 Espressif Aarduino package. Even the recent version has this problem. I'm using the v 2.0.15

I've opened a new Case https://github.com/espressif/arduino-esp32/issues/9571 isolating the problem in the minimum code example

**Comment by mobizt** [comment]
It is up to you, but your hardware failure is true.

All devices and platform list here included all ESP32 variants are working normally.
https://github.com/mobizt/ESP-Mail-Client?tab=readme-ov-file#supported-devices
