### ISSUE TITLE
IMAP and SMPT example combined produce a crash with ESP8266 

### ISSUE THREAD

**Issue by pberna67** [mobizt/ESP-Mail-Client#342]
Dear Developer

It seems that combining the SMTP **Send_text.ino** and the IMAP **Mailbox_Changes_Notification.ino** in a ESP8266 platform, into a single project (to have the capability to send and receive mails) the combined project (attached) crashed, however each project runs independently correctly. At the moment is not yet clear if the problem is located somewhere in your code on in the below libraries

I've noticed that the same projects (combined version and separated version), compiled under the ES32 environment work correctly.

Arduino Configuration

![image](https://github.com/mobizt/ESP-Mail-Client/assets/17097864/2cbd31ec-e665-428d-bb7d-629d5bd4bd35)

Serial console report

:15:26.489 -> scandone
13:15:26.489 -> 
13:15:26.631 -> Connecting to Wi-Fi..........scandone
13:15:30.556 -> state: 0 -> 2 (b0)
13:15:30.556 -> .state: 2 -> 3 (0)
13:15:30.556 -> state: 3 -> 5 (10)
13:15:30.556 -> add 0
13:15:30.556 -> aid 1
13:15:30.556 -> cnt 
13:15:30.556 -> 
13:15:30.556 -> connected with WIND-WiFi-C69F, channel 4
13:15:30.603 -> dhcp client start...
13:15:30.836 -> ........ip:192.168.10.182,mask:255.255.255.0,gw:192.168.10.150
13:15:33.220 -> 
13:15:33.220 -> Connected with IP: 192.168.10.182
13:15:33.266 -> 
13:15:33.266 -> #### Connecting to IMAP server...
13:15:33.266 -> > C: ESP Mail Client v3.4.19
13:15:33.266 -> > C: Reading time from NTP server..
13:15:33.312 -> > C: connecting to IMAP server
13:15:33.312 -> > C: Host > imapmail.libero.it
13:15:33.312 -> > C: Port > 993
13:15:34.576 -> 
13:15:34.576 -> #### IMAP server connected
13:15:34.576 -> > C: IMAP server connected
13:15:34.622 -> 
13:15:34.622 -> #### Checking the capability...
13:15:34.622 -> > C: check the capability
13:15:34.716 -> 
13:15:34.716 -> #### Logging in...
13:15:34.716 -> > C: send IMAP command, AUTHENTICATE PLAIN
13:15:34.856 -> 
13:15:34.856 -> #### Send client identification...
13:15:34.856 -> > C: send IMAP command, ID
13:15:35.043 -> Successfully logged in.
13:15:35.043 -> 
13:15:35.043 -> #### Reading the list of mailboxes...
13:15:35.043 -> > C: send IMAP command, LIST
13:15:35.182 -> 
13:15:35.182 -> Available folders: Posta inviata, Posta eliminata, Posta indesiderata, trash, outbox, Spam, draft, INBOX
13:15:35.182 -> 
13:15:35.182 -> #### Open the mailbox folder...
13:15:35.182 -> > C: selecting the INBOX folder...
13:15:35.323 -> 
13:15:35.323 -> Info of the selected folder
13:15:35.323 -> Total Messages: 329
13:15:35.323 -> UID Validity: 1713786152
13:15:35.323 -> Predicted next UID: 1951
13:15:35.323 -> First Unseen Message Number: 5
13:15:35.323 -> Highest Modification Sequence: 2246
13:15:35.323 -> Flags: \Answered, \Flagged, \Deleted, \Seen, \Draft
13:15:35.323 -> #### Connecting to SMTP server...
13:15:35.323 -> > C: ESP Mail Client v3.4.19
13:15:35.323 -> > C: connecting to SMTP server
13:15:35.323 -> > C: Host > smtp.libero.it
13:15:35.323 -> > C: Port > 465
13:15:37.430 -> 
13:15:37.430 -> #### SMTP server connected
13:15:37.430 -> > C: SMTP server connected, wait for greeting...
13:15:37.430 -> < S: 220 smtp-34.iol.local smtp-34.iol.local ESMTP server ready
13:15:37.430 -> 
13:15:37.430 -> #### Sending greeting response...
13:15:37.430 -> > C: send SMTP command, EHLO
13:15:37.525 -> < S: 250-smtp-34.iol.local hello [151.36.230.109], pleased to meet you
13:15:37.525 -> < S: 250-HELP
13:15:37.525 -> < S: 250-AUTH LOGIN PLAIN
13:15:37.525 -> < S: 250-SIZE 50000000
13:15:37.525 -> < S: 250-8BITMIME
13:15:37.525 -> < S: 250 OK
13:15:37.525 -> 
13:15:37.525 -> #### Logging in...
13:15:37.525 -> > C: send SMTP command, AUTH PLAIN
13:15:37.525 -> > C: videocamera.nella@libero.it
13:15:37.525 -> > C: ************
13:15:37.666 -> < S: 235 ... authentication succeeded
13:15:37.666 -> Successfully logged in.
13:15:37.666 -> 
13:15:37.666 -> #### Sending Email...
13:15:37.666 -> > C: send Email
13:15:37.666 -> 
13:15:37.666 -> #### Sending message header...
13:15:37.666 -> > C: send message header
13:15:37.760 -> < S: 250 <videocamera.nella@libero.it> sender ok
13:15:37.856 -> < S: 250 <videocamera.nella@libero.it> recipient ok
13:15:37.903 -> 
13:15:37.903 -> #### Sending message body...
13:15:37.903 -> > C: send message body
13:15:37.950 -> < S: 354 OK
13:15:38.091 -> 
13:15:38.091 -> #### Finishing the message sending...
13:15:38.091 -> > C: finishing the message sending
13:15:38.184 -> < S: 250 4InJs1xXl4z9K4InJs9zH9 mail accepted for delivery
13:15:38.184 -> 
13:15:38.184 -> #### Closing the session...
13:15:38.184 -> > C: terminate the SMTP session
13:15:38.184 -> 
13:15:38.184 -> #### Message sent successfully
13:15:38.184 -> > C: message sent successfully
13:15:38.230 -> 
13:15:38.230 -> ----------------
13:15:38.230 -> Message sent success: 1
13:15:38.230 -> Message sent failed: 0
13:15:38.230 -> ----------------
13:15:38.230 -> 
13:15:38.230 -> Message No: 1
13:15:38.230 -> Status: success
13:15:38.230 -> Date/Time: May 07, 2024 14:15:37
13:15:38.230 -> Recipient: videocamera.nella@libero.it
13:15:38.230 -> Subject: Test Subject
13:15:38.230 -> ----------------
13:15:38.230 -> 
13:15:38.230 -> 
13:15:38.230 -> #### Listening to mailbox changes...
13:15:38.230 -> > C: listening to INBOX folder changes
13:15:38.370 -> 
13:15:38.370 -> #### Polling established
13:15:38.370 -> > C: polling established on May 07, 2024 14:15:38
13:15:38.370 -> STATO WIFI : 3
13:15:38.370 -> RSSI: -61
13:15:38.370 -> Connected with IP: 192.168.10.182
13:15:38.370 -> IS NOT KEEP ALIVE
13:15:38.370 -> IMAP CONNECTED
13:15:38.370 -> 
13:15:38.370 -> 
13:15:38.370 -> Mailbox status changed
13:15:38.370 -> ----------------------
13:15:38.370 -> Total Messages: 330
13:15:38.370 -> New message 330, has been addedd, reading message...
13:15:38.463 -> 
13:15:38.463 -> #### Mailbox listening stopped
13:15:38.463 -> > C: Mailbox listening stopped
13:15:38.463 -> 
13:15:38.463 -> #### Get UID...
13:15:38.463 -> > C: get UID
13:15:38.556 -> 
13:15:38.556 -> #### UID is 1951
13:15:38.556 -> > C: UID is 1951
13:15:38.602 -> 
13:15:38.602 -> #### Fetch message 1, UID: 1951
13:15:38.602 -> > C: send IMAP command, FETCH
13:15:38.602 -> > C: fetch message header
13:15:38.743 -> Fatal exception 3(LoadStoreErrorCause):
13:15:38.743 -> epc1=0x4020e306, epc2=0x00000000, epc3=0x00000000, excvaddr=0x4027cc10, depc=0x00000000
13:15:38.743 -> 
13:15:38.743 -> --------------- CUT HERE FOR EXCEPTION DECODER ---------------
13:15:38.743 -> 
13:15:38.743 -> Exception (3):
13:15:38.743 -> epc1=0x4020e306 epc2=0x00000000 epc3=0x00000000 excvaddr=0x4027cc10 depc=0x00000000
13:15:38.790 -> 
13:15:38.790 -> >>>stack>>>
13:15:38.790 -> 
13:15:38.790 -> ctx: cont
13:15:38.790 -> sp: 3fff1050 end: 3fff1720 offset: 0150
13:15:38.790 -> 3fff11a0:  00000005 00000000 00000a10 40100d1c  
13:15:38.790 -> 3fff11b0:  00000000 00000001 00000004 3fff7b00  
13:15:38.790 -> 3fff11c0:  40100894 00000001 00000020 3fff0440  
13:15:38.790 -> 3fff11d0:  00000000 ffffffff 00000000 4020e4e9  
13:15:38.790 -> 3fff11e0:  3fff6aa4 3fff6946 3fff0498 402058f4  
13:15:38.790 -> 3fff11f0:  3fff6f8c 00000005 3fff1224 3fff7af4  
13:15:38.790 -> 3fff1200:  3fff12c0 3fff0440 00000026 4020f1cf  
13:15:38.790 -> 3fff1210:  00000000 00000000 00000b7d 40100d1c  
13:15:38.836 -> 3fff1220:  00005be8 3fff6aa4 00000008 40100a6a  
13:15:38.836 -> 3fff1230:  3fff7af4 00000020 3fff6f84 00000000  
13:15:38.836 -> 3fff1240:  00000002 00000020 3fff7aec 40100eaa  
13:15:38.836 -> 3fff1250:  3fff6aa4 3fff0440 3fff1558 3fff12c0  
13:15:38.836 -> 3fff1260:  00000004 3fff0440 3ffefffc 40218841  
13:15:38.836 -> 3fff1270:  00000000 3fff1520 00000002 4010242c  
13:15:38.836 -> 3fff1280:  00000001 3fff769c 00000036 000030c9  
13:15:38.836 -> 3fff1290:  00000400 00000009 00010101 00000182  
13:15:38.836 -> 3fff12a0:  3fff69ec 00000054 3fff6fac 00000004  
13:15:38.836 -> 3fff12b0:  3fff6984 00000038 3fff6894 00000004  
13:15:38.882 -> 3fff12c0:  3fff692c 00000020 3fff6a54 00000020  
13:15:38.882 -> 3fff12d0:  3fff764c 00000018 3fff761c 00000020  
13:15:38.882 -> 3fff12e0:  00000000 00000000 00000000 00000000  
13:15:38.882 -> 3fff12f0:  00000000 00000000 00000000 00000000  
13:15:38.882 -> 3fff1300:  00000000 00000000 00000000 00000000  
13:15:38.882 -> 3fff1310:  00000000 00000000 3fff6a84 0000000c  
13:15:38.882 -> 3fff1320:  3fff69cc 00000008 0000079f 0000014a  
13:15:38.882 -> 3fff1330:  00000000 00000000 00000000 00000000  
13:15:38.882 -> 3fff1340:  00000000 00000000 3fff7b34 0000000c  
13:15:38.882 -> 3fff1350:  40000000 00000000 00000000 00000000  
13:15:38.882 -> 3fff1360:  00000000 00000000 00000000 00000000  
13:15:38.928 -> 3fff1370:  00000000 00000000 00000000 00000000  
13:15:38.928 -> 3fff1380:  00000300 00000000 00000000 00000000  
13:15:38.928 -> 3fff1390:  00000000 00000000 00000000 00000000  
13:15:38.928 -> 3fff13a0:  00000000 00000000 00000000 00000000  
13:15:38.928 -> 3fff13b0:  00000000 00000000 00000000 4023a200  
13:15:38.928 -> 3fff13c0:  00000000 00000000 ffffffff 00000000  
13:15:38.928 -> 3fff13d0:  00000000 00000000 00000000 00000000  
13:15:38.928 -> 3fff13e0:  00000000 00000000 00000000 00000000  
13:15:38.928 -> 3fff13f0:  00000000 00000000 00000000 00000000  
13:15:38.928 -> 3fff1400:  00000000 00000000 00000000 00000000  
13:15:38.975 -> 3fff1410:  00000000 00000000 00000000 00000000  
13:15:38.975 -> 3fff1420:  00000000 00000000 00000000 00000000  
13:15:38.975 -> 3fff1430:  00000000 00000000 00000000 00000000  
13:15:38.975 -> 3fff1440:  00000000 00000000 00000000 00000000  
13:15:38.975 -> 3fff1450:  00000000 00000000 00000000 00000000  
13:15:38.975 -> 3fff1460:  01000000 00000000 00000000 00000000  
13:15:38.975 -> 3fff1470:  00000000 00000000 00000000 00000000  
13:15:38.975 -> 3fff1480:  00000000 00000000 00000000 00000000  
13:15:38.975 -> 3fff1490:  00000000 00000000 00000000 00000000  
13:15:38.975 -> 3fff14a0:  00000000 00000000 00000000 00000000  
13:15:38.975 -> 3fff14b0:  00000000 00000000 00000000 00000000  
13:15:39.021 -> 3fff14c0:  00000000 00000000 00000000 00000000  
13:15:39.021 -> 3fff14d0:  00000000 00000000 00000000 00000000  
13:15:39.021 -> 3fff14e0:  00000000 00000000 00000000 00000000  
13:15:39.021 -> 3fff14f0:  3f000000 00000000 00000000 00000000  
13:15:39.021 -> 3fff1500:  40278500 000001bf 00000000 00000000  
13:15:39.021 -> 3fff1510:  00000013 00000000 00000000 00000000  
13:15:39.021 -> 3fff1520:  00000000 00000000 3ffe8c4c 40100a6a  
13:15:39.021 -> 3fff1530:  3ffe97dd 00000000 00000002 4020b9a9  
13:15:39.021 -> 3fff1540:  00000001 0000079f 00000001 0000079f  
13:15:39.021 -> 3fff1550:  3fff7674 00000010 00000000 402058f4  
13:15:39.069 -> 3fff1560:  3fff6a84 3fff1480 3fff00d0 00000000  
13:15:39.069 -> 3fff1570:  00000187 ffffff35 00000000 fffffff7  
13:15:39.069 -> 3fff1580:  00000000 3ffefffc 3fff0440 40218ab0  
13:15:39.069 -> 3fff1590:  4027cf43 0000001e 3fff15e4 3fff0440  
13:15:39.069 -> 3fff15a0:  3ffefffc 4027b3ef 3fff00fc 4021e275  
13:15:39.069 -> 3fff15b0:  3fff6918 3ffe8c4c 0000094c 40100bbc  
13:15:39.069 -> 3fff15c0:  00000000 00000000 3fff68d8 00000000  
13:15:39.069 -> 3fff15d0:  3fff6914 3ffe8c4c 3fff6ae8 3fff742c  
13:15:39.069 -> 3fff15e0:  000000cc 3fff750c 000000fc 00000000  
13:15:39.069 -> 3fff15f0:  00000000 00000000 00000000 00000000  
13:15:39.069 -> 3fff1600:  00000000 3ffe8c4c 3fff68d8 40100962  
13:15:39.116 -> 3fff1610:  00000000 00000001 00000000 40100962  
13:15:39.116 -> 3fff1620:  00000001 00000000 00000001 3fff00f8  
13:15:39.116 -> 3fff1630:  3fff0068 00000941 3ffe8c4c 40100a6a  
13:15:39.116 -> 3fff1640:  3fff6914 00000000 00000000 00000000  
13:15:39.116 -> 3fff1650:  3ffefdfc 00000020 3fff690c 0000079f  
13:15:39.116 -> 3fff1660:  3ffefdfc 3ffefffc 3fff0440 40206a81  
13:15:39.116 -> 3fff1670:  0000014a 00000000 66264d28 0000079f  
13:15:39.116 -> 3fff1680:  00000005 3fff4c94 00000008 00000000  
13:15:39.116 -> 3fff1690:  00000000 00002f3f 00000101 00000001  
13:15:39.116 -> 3fff16a0:  0000014a 00000000 00000000 3fff6b2c  
13:15:39.116 -> 3fff16b0:  3fff6b54 3fff6b54 00000000 00000000  
13:15:39.163 -> 3fff16c0:  00000000 00000001 0000014a 00000000  
13:15:39.163 -> 3fff16d0:  00000000 3ffe97dd 3fff054c 3fff177c  
13:15:39.163 -> 3fff16e0:  3fff0414 3ffefffc 3fff054c 40206beb  
13:15:39.163 -> 3fff16f0:  4022ce48 b60aa8c0 feefeffe 3fff177c  
13:15:39.163 -> 3fff1700:  3fffdad0 00000000 3fff1750 4022982c  
13:15:39.163 -> 3fff1710:  feefeffe feefeffe 3fffdab0 401011e1  
13:15:39.163 -> <<<stack<<<

[ImapSmptComboDebug_github.zip](https://github.com/mobizt/ESP-Mail-Client/files/15234855/ImapSmptComboDebug_github.zip)

**Comment by mobizt** [comment]
It is normal as expected because out of memory.

You have to use Raspberry Pi Pico or ESP32 instead.

**Comment by pberna67** [comment]
correct, with the right memory setting it works. Thanks
