### ISSUE TITLE
Some warnings

### ISSUE THREAD

**Issue by vpapanik** [mobizt/ESP-Mail-Client#359]
**Build tool used:**

- [X ] Arudino
- [ ] Platformio (Visual Studio Code plugin)
- [ ] Platformio CLI
- [ ] Other

**Board used (ESP32/ESP8266/Arudino):**

- [X ] ESP8266-based
- [ ] ESP32-based

**Other Libraries That are used:**

**Description of problem:**

Found some warnings : 

In file included from c:\Users\<>\Documents\Arduino\libraries\ESP_Mail_Client\src\ESP_Mail_Client.cpp:42:

c:\Users\<>\Documents\Arduino\libraries\ESP_Mail_Client\src\ESP_Mail_SMTP.h: In member function 'void ESP_Mail_Client::getResponseStatus(const char*, esp_mail_smtp_status_code, int, esp_mail_smtp_response_status_t&)':

c:\Users\<>\Documents\Arduino\libraries\ESP_Mail_Client\src\ESP_Mail_SMTP.h:2964:25: warning: comparison of integer expressions of different signedness: 'size_t' {aka 'unsigned int'} and 'int' [-Wsign-compare]

 2964 |         if (strlen(buf) > numLen && (buf[numLen] == ' ' || buf[numLen] == '-') && textLen > 0)
      |             ~~~~~~~~~~~~^~~~~~~~

c:\Users\<>\Documents\Arduino\libraries\ESP_Mail_Client\src\ESP_Mail_SMTP.h:2985:26: warning: comparison of integer expressions of different signedness: 'int' and 'size_t' {aka 'unsigned int'} [-Wsign-compare]

 2985 |                 while (i < strlen(buf) && buf[i] != ' ')
      |                        ~~^~~~~~~~~~~~~

c:\Users\<>\Documents\Arduino\libraries\ESP_Mail_Client\src\ESP_Mail_SMTP.h:2989:24: warning: comparison of integer expressions of different signedness: 'int' and 'size_t' {aka 'unsigned int'} [-Wsign-compare]

 2989 |                 i = (i < strlen(buf) - 1) ? i + 1 : numLen + 1;
      |                      ~~^~~~~~~~~~~~~~~~~

**Share code snippet to reproduce the issue:**
```yaml
PASTE .cpp / .ino code here

```

**Additional information and things you've tried:**

**Comment by mobizt** [comment]
No effect with the library working.
