### ISSUE TITLE
I am facing compilation error please help me out. 

### ISSUE THREAD

**Issue by Hritadipdatta** [mobizt/ESP-Mail-Client#363]
C:\Users\hrita\OneDrive\Desktop\3rd year 5th SEMISTER ALL BOOKS\Arduino Project II\ESP32_Cam_based_Motion_Triggered_Image_Capturing_Device\ESP32_Cam_based_Motion_Triggered_Image_Capturing_Device.ino:7:10: fatal error: ESP32_MailClient.h: No such file or directory
    7 | #include "ESP32_MailClient.h"
      |          ^~~~~~~~~~~~~~~~~~~~
compilation terminated.
Alternatives for ESP32_MailClient.h: []
ResolveLibrary(ESP32_MailClient.h)
  -> candidates: []
exit status 1

Compilation error: ESP32_MailClient.h: No such file or directory

**Comment by mobizt** [comment]
That library is deprecatedvand end of life.
