### ISSUE TITLE
Send Email over GSM error

### ISSUE THREAD

**Issue by Jvf01** [mobizt/ESP-Mail-Client#366]
**Build tool used:**

- [x ] Arudino
- [ ] Platformio (Visual Studio Code plugin)
- [ ] Platformio CLI
- [ ] Other

**Board used (ESP32/ESP8266/Arudino):**

- [ ] ESP8266-based
- [ x] ESP32-based

**Other Libraries That are used:**

I bought a LILLY TTGO A7670e card and I'm trying to send an email via GSM (4G?).
It gives the error "#### Error, connection closed
! E: connection closed" which I can't get past.

I think that the error occurs with the statement :

  smtp.connect(&config);

[Log_Email_error.docx](https://github.com/user-attachments/files/17753162/Log_Email_error.docx)

**Share code snippet to reproduce the issue:**
// For TTGO T-A7670
#define TINY_GSM_MODEM_A7670 // SIMA7670 Compatible with SIM7600 AT instructions

// Set serial for debug console (to the Serial Monitor, default speed 115200)
#define SerialMon Serial

// Set serial for AT commands (to the module)
// Use Hardware Serial on Mega, Leonardo, Micro
#define SerialAT Serial1

#include <ESP_Mail_Client.h>
#include <TinyGsmClient.h>

// See all AT commands, if wanted
// #define DUMP_AT_COMMANDS

// Define the serial console for debug prints, if needed
#define TINY_GSM_DEBUG SerialMon

#define TINY_GSM_USE_GPRS true
#define TINY_GSM_USE_WIFI false

// set GSM PIN, if any
#define GSM_PIN ""

#define SMTP_HOST "smtp.gmail.com"
#define SMTP_PORT 465

//  The sign in credentials 
#define AUTHOR_EMAIL "routertico@gmail.com"
#define AUTHOR_PASSWORD "xxxxxxxxxxxx"
// #define AUTHOR_PASSWORD "Gatinha1%"

//  Recipient's email
#define RECIPIENT_EMAIL "joaquim.v.fernandes@gmail.com"

SMTPSession smtp;

// Callback function to get the Email sending status
void smtpCallback(SMTP_Status status);

// Your GPRS credentials, if any
const char apn[] = "umts";
const char gprsUser[] = "";
const char gprsPass[] = "";

#define uS_TO_S_FACTOR 1000000ULL // Conversion factor for micro seconds to seconds
#define TIME_TO_SLEEP 600         // Time ESP32 will go to sleep (in seconds)

#define UART_BAUD 115200
#define PIN_DTR 25
#define PIN_TX 26
#define PIN_RX 27
#define PWR_PIN 4
#define BAT_ADC 35
#define BAT_EN 12
#define PIN_RI 33
#define PIN_DTR 25
#define RESET 5
#define SD_MISO 2
#define SD_MOSI 15
#define SD_SCLK 14
#define SD_CS 13

#define MODEM_BAUDRATE                      (115200)
#define MODEM_DTR_PIN                       (25)
#define MODEM_TX_PIN                        (26)
#define MODEM_RX_PIN                        (27)
// The modem boot pin needs to follow the startup sequence.
#define BOARD_PWRKEY_PIN                    (4)
#define BOARD_ADC_PIN                       (35)
// The modem power switch must be set to HIGH for the modem to supply power.
#define BOARD_POWERON_PIN                   (12)
#define MODEM_RING_PIN                      (33)
#define MODEM_RESET_PIN                     (5)
#define BOARD_MISO_PIN                      (2)
#define BOARD_MOSI_PIN                      (15)
#define BOARD_SCK_PIN                       (14)
#define BOARD_SD_CS_PIN                     (13)
#define BOARD_BAT_ADC_PIN                   (35)
#define MODEM_RESET_LEVEL                   HIGH
#define SerialAT                            Serial1

#define MODEM_GPS_ENABLE_GPIO               (-1)

TinyGsm modem(SerialAT);
TinyGsmClient gsm_client(modem);      // basic non-secure client

void setup(){

    delay(1000);
    Serial.println("Inicio ");

  SerialMon.begin(115200);
  // Set debug option
  smtp.debug(1);

  // Set the callback function to get the sending results
  smtp.callback(smtpCallback);

  ligamodemegsm();

  /*
  2 Automatic
  13 GSM Only
  14 WCDMA Only
  38 LTE Only
  */
  if (!modem.setNetworkMode(MODEM_NETWORK_LTE)) {
      Serial.println("Set network mode failed!");
  }
  String mode = modem.getNetworkModes();
  Serial.print("Current network mode : ");
  Serial.println(mode);

  Session_Config config;

  config.server.host_name = SMTP_HOST;
  config.server.port = SMTP_PORT;
  config.login.email = AUTHOR_EMAIL;
  config.login.password = AUTHOR_PASSWORD;
  config.login.user_domain ="";
  // config.login.user_domain = F("127.0.0.1");

  // Declare the SMTP_Message class variable to handle to message being transport
  SMTP_Message message;

  // Set the message headers
  message.sender.name = F("JVF");
  message.sender.email = AUTHOR_EMAIL;
  message.subject = F("Test sending plain text Email using GSM module");
  message.addRecipient(F("Someone"), RECIPIENT_EMAIL);

  // Set the message content
  message.text.content = "This is simple plain text message";
 
  // Set debug option
  smtp.debug(1);

  // Set the callback function to get the sending results
  smtp.callback(smtpCallback);

  smtp.setGSMClient(&gsm_client, &modem, GSM_PIN, apn, gprsUser, gprsPass);

  // Connect to the server with the defined session and options
  smtp.connect(&config);

  // Start sending Email and close the session
  if (!MailClient.sendMail(&smtp, &message))
    Serial.println("Error sending Email, " + smtp.errorReason());
}

void loop()
{
}

void smtpCallback(SMTP_Status status)
{
 
  Serial.println(status.info());

  if (status.success())
  {
    // See example for how to get the sending result
  }
}

void ligamodemegsm() {

// Turn on DC boost to power on the modem
  #ifdef BOARD_POWERON_PIN
    pinMode(BOARD_POWERON_PIN, OUTPUT);
    digitalWrite(BOARD_POWERON_PIN, HIGH);
  #endif
  // Set modem reset pin ,reset modem
  pinMode(MODEM_RESET_PIN, OUTPUT);
  digitalWrite(MODEM_RESET_PIN, !MODEM_RESET_LEVEL);
  delay(100);
  digitalWrite(MODEM_RESET_PIN, MODEM_RESET_LEVEL);
  delay(2600);
  digitalWrite(MODEM_RESET_PIN, !MODEM_RESET_LEVEL);
  // Turn on modem
  pinMode(BOARD_PWRKEY_PIN, OUTPUT);
  digitalWrite(BOARD_PWRKEY_PIN, LOW);
  delay(100);
  digitalWrite(BOARD_PWRKEY_PIN, HIGH);
  delay(1000);
  digitalWrite(BOARD_PWRKEY_PIN, LOW);
  // Set ring pin input
  pinMode(MODEM_RING_PIN, INPUT_PULLUP);
  // Set modem baud
  SerialAT.begin(115200, SERIAL_8N1, MODEM_RX_PIN, MODEM_TX_PIN);
  Serial.println("Start modem...");
  delay(500);

  // while (!modem.testAT()) {
  //     delay(10);
  // }
  int retry = 0;
  while (!modem.testAT(1000)) {
    Serial.println(".");
    if (retry++ > 10) {
      digitalWrite(BOARD_PWRKEY_PIN, LOW);
      delay(100);
      digitalWrite(BOARD_PWRKEY_PIN, HIGH);
      delay(1000);
      digitalWrite(BOARD_PWRKEY_PIN, LOW);
      retry = 0;
    }
  }
  Serial.println();

  String modemName = "UNKOWN";
  while (1) {
    modemName = modem.getModemName();
    if (modemName == "UNKOWN") {
      Serial.println("Unable to obtain module information normally, try again");
      delay(1000);
    } else if (modemName.startsWith("SIM7670")) {
      while (1) {
        Serial.println("SIM7670 does not support SMS Function");
        delay(1000);
      }
    } else {
      Serial.print("Model Name:");
      Serial.println(modemName);
      break;
    }
    delay(5000);
  }

  // Wait PB DONE
  Serial.println("Wait SMS Done.");
  if (!modem.waitResponse(100000UL, "SMS DONE")) {
    Serial.println("Can't wait from sms register ....");
    return;
  }

  #ifdef NETWORK_APN
    Serial.printf("Set network apn : %s\n", NETWORK_APN);
    modem.sendAT(GF("+CGDCONT=1,\"IP\",\""), NETWORK_APN, "\"");
    if (modem.waitResponse() != 1) {
      Serial.println("Set network apn error !");
    
    } else {
      Serial.println("Set network apn success !");
    
    }
  #endif

  // Check if SIM card is online
  SimStatus sim = SIM_ERROR;
  while (sim != SIM_READY) {
    sim = modem.getSimStatus();
    switch (sim) {
      case SIM_READY:
        Serial.println("SIM card online");
        break;
      case SIM_LOCKED:
        Serial.println("The SIM card is locked. Please unlock the SIM card first.");
        // const char *SIMCARD_PIN_CODE = "123456";
        // modem.simUnlock(SIMCARD_PIN_CODE);
        break;
      default:
        break;
    }
    delay(1000);
  }

  // Check network registration status and network signal status
  int16_t sq;
  Serial.println("Wait for the modem to register with the network.");
  RegStatus status = REG_NO_RESULT;
  int gsmct = 0;
  while ((status == REG_NO_RESULT || status == REG_SEARCHING || status == REG_UNREGISTERED) && gsmct < 30) {
    gsmct++;
    status = modem.getRegistrationStatus();
    switch (status) {
      case REG_UNREGISTERED:
      case REG_SEARCHING:
        sq = modem.getSignalQuality();
        Serial.printf("[%lu] Signal Quality:%d\n", millis() / 1000, sq);
        delay(1000);
        break;
      case REG_DENIED:
        Serial.println("Network registration was rejected, please check if the APN is correct");
        
        return;
      case REG_OK_HOME:
        Serial.println("Online registration successful");
        
        break;
      case REG_OK_ROAMING:
        Serial.println("Network registration successful, currently in roaming mode");
       
        break;
      default:
        Serial.printf("Registration Status:%d\n", status);
        delay(1000);
        break;
    }
  }

  Serial.println();
  Serial.printf("Registration Status:%d\n", status);
  delay(1000);

  String ueInfo;
  if (modem.getSystemInformation(ueInfo)) {
    Serial.print("Inquiring UE system information:");
    Serial.println(ueInfo);
  }

  if (!modem.enableNetwork()) {
    Serial.println("Enable network failed!");
  }

  delay(5000);
  // enviawapp("");
}

```

**Additional information and things you've tried:**
[Log_Email_error.docx](https://github.com/user-attachments/files/17753231/Log_Email_error.docx)




<!-- LEAVE THIS LINE AS-IS AND DON'T DELETE IT, OTHERWISE THE ISSUE WILL BE CLOSED AUTOMATICALLY. -->

**Comment by mobizt** [comment]
The error shows that library cannot operate your GSM module with TinyGSM library because it was not properly setup, please follow and read the comments in [this example](https://github.com/mobizt/ESP-Mail-Client/blob/master/examples/SMTP/External_Client/GSMClient/ESP32_SIMA7670/ESP32_SIMA7670.ino) thoroughly.

**Comment by mobizt** [comment]
https://github.com/mobizt/ESP-Mail-Client/blob/86cab269d4b3eb58de1de680e959c3d82482bb5d/examples/SMTP/External_Client/GSMClient/ESP32_SIMA7670/ESP32_SIMA7670.ino#L32-L34

**Comment by mobizt** [comment]
There is no macro that you define `TINY_GSM_MODEM_A7670` in TinyGSM library, where did you get it from?https://github.com/vshymanskyy/TinyGSM/blob/master/src/TinyGsmClient.h

Please spend the time to learn and play with TinyGSM library to make sure that you use it correctly.

As you see in this library example comment, you just to follow it because `SIMA7670` and `SIM7600` AT instructions are compatible.
https://github.com/mobizt/ESP-Mail-Client/blob/86cab269d4b3eb58de1de680e959c3d82482bb5d/examples/SMTP/External_Client/GSMClient/ESP32_SIMA7670/ESP32_SIMA7670.ino#L36

**Comment by Jvf01** [comment]
In my project i´m using the libraries from "https://github.com/Xinyuan-LilyGO/LilyGO-T-A76XX/tree/main/lib" that support teh borad TTGO A7670E that i bought.

I´m sorry but I don't quite understand what it means " // To allow TinyGSM library integration, the following macro should be defined in src/ESP_Mail_FS.h or 
 // your custom config file src/Custom_ESP_Mail_FS.h. 
 //  #define TINY_GSM_MODEM_SIM7600 "

ok, thank you and best regards

**Comment by mobizt** [comment]
You have to use this [TinyGSM](https://github.com/vshymanskyy/TinyGSM) from the developer repo instead of modified version, otherwise you cannot use this Email library.

Did you read this line of example comment?
https://github.com/mobizt/ESP-Mail-Client/blob/86cab269d4b3eb58de1de680e959c3d82482bb5d/examples/SMTP/External_Client/GSMClient/ESP32_SIMA7670/ESP32_SIMA7670.ino#L12

It means that it uses TTGO T-A7670 which is the same board as yours.

https://github.com/mobizt/ESP-Mail-Client/blob/86cab269d4b3eb58de1de680e959c3d82482bb5d/examples/SMTP/External_Client/GSMClient/ESP32_SIMA7670/ESP32_SIMA7670.ino#L32-L34

The above comment in the example shows that, you have to edit [this config file](https://github.com/mobizt/ESP-Mail-Client/blob/86cab269d4b3eb58de1de680e959c3d82482bb5d/src/ESP_Mail_FS.h#L168) by adding this code `#define TINY_GSM_MODEM_SIM7600` in that file and also in your sketch.

**Comment by Jvf01** [comment]
Thank you very much for your help..... i will try it and give you my feed
back.
Best regards

A quinta, 14/11/2024, 23:55, Suwatchai K. ***@***.***>
escreveu:

**Comment by Jvf01** [comment]
It's solved.... it's working

Thank you

A quinta, 14/11/2024, 23:55, Suwatchai K. ***@***.***>
escreveu:
