### ISSUE TITLE
If ESP32 is not connected to the Internet

### ISSUE THREAD

**Issue by vowovrz** [mobizt/ESP-Mail-Client#43]
If ESP32 is not connected to the Internet, the program will stop: Error, unable to connect to server, how to prevent the program from being stopped

**Comment by mobizt** [comment]
You need to manage this yourself.
Don't you know WiFi and BLE use the same (shared) radio module? 

Then WiFi and BLE can't work simultaneously.
You need to stop BLE before use the WiFi and you need to stop WiFi when you use BLE.

**Comment by mobizt** [comment]
Next time if you have the questions, please use [discussions](https://github.com/mobizt/ESP-Mail-Client/discussions).
