### ISSUE TITLE
Can't add String to text message

### ISSUE THREAD

**Issue by floatAsNeeded** [mobizt/ESP-Mail-Client#47]
Hi!

I was just using your library and I found it very useful! I was just wondering if was possibile to also send some String in the text message in the email.

For example:

` message.html.content = "<br>Temperature is " + String(temp, 1) + "°C<br>Humidity is " + String(humidity) + "%<br>Pressure is " + String(pressurehpa, 1) + "hPa<br>Wind Speed is " + String(WindSpeed, 1) + "km/h from " + DIRECTIONWIND + "<br>Rain Today " + String(mmPioggia, 1) + "mm<br>Rain Intensity is " + String(rainrate, 1) + "mm/h<br>Current UV is " + String(UVindex) + "<br><br><b>Daily Weather Observations</b><br><br>Highest " + String(maxTemp, 1) + "°C<br>Lowest " + String(minTemp, 1) + "°C<br>Gust " + String(Gust, 1) + "km/h<br>Maximum Intensity of Rain " + String(rainrateMax, 1) + "mm/h<br><br><i>To stop this notification go to Services/EmailAlert/EmailNotification and type 'OFF'</i>";`
     

At the moment it gives an error if I try to do that. The Strings are variable.

And also, is it possible to have the possibility to be a variable also the String of the email of the recipient?

For example.

```
String email = "example@gmail.com";

 message.addRecipient("Admin", email);

```

Much appreciate for some feedback!

Thank you!

**Comment by mobizt** [comment]
Use c_str() function from String to get the const char array of the string like this.

```cpp
String html_msg =  "<br>Temperature is " + String(temp, 1) + "°C<br>Humidity is " + String(humidity) + "%<br>Pressure is " + String(pressurehpa, 1) + "hPa<br>Wind Speed is " + String(WindSpeed, 1) + "km/h from " + DIRECTIONWIND + "<br>Rain Today " + String(mmPioggia, 1) + "mm<br>Rain Intensity is " + String(rainrate, 1) + "mm/h<br>Current UV is " + String(UVindex) + "<br><br><b>Daily Weather Observations</b><br><br>Highest " + String(maxTemp, 1) + "°C<br>Lowest " + String(minTemp, 1) + "°C<br>Gust " + String(Gust, 1) + "km/h<br>Maximum Intensity of Rain " + String(rainrateMax, 1) + "mm/h<br><br><i>To stop this notification go to Services/EmailAlert/EmailNotification and type 'OFF'</i>";

message.html.content = html_msg.c_str();


String email = "example@gmail.com";

message.addRecipient("Admin", email.c_str());
```
