### ISSUE TITLE
can't add Recipient from string variavle

### ISSUE THREAD

**Issue by helioesperidiao** [mobizt/ESP-Mail-Client#48]
Hi.
Im trying to add names and emails from an array, but i always get: "error sending Email, some of the recipient Email address is not valid", but i know for sure that the contents of the string variable are rigth. Sorry my English is very poor.  Please Help :)

int i=0;

 while(i<10){
          String tempNomes = NOMES[i] ;
          String tempMails = MAILS[i]';
         

 if(tempMails.length()>5){
            message.addRecipient(&tempNomes[0],&tempMails[0]);
}
    
    i++;
  }

**Comment by mobizt** [comment]
Use this

**message.addRecipient(tempNomes.c_str(),tempMails.c_str());**

You can use [Discussions](https://github.com/mobizt/ESP-Mail-Client/discussions) for the question.
