### ISSUE TITLE
run led

### ISSUE THREAD

**Issue by pyrismian** [mobizt/ESP-Mail-Client#49]
How to operate led (Esp32 gpio 2) with the email matching received with hi imap.
#define textmessage1 "on"
#define textmessage2 "off"
.
.
.
.
if(msg.text.content == textmessage1){
digitalWrite(2,HIGH);
}
if(msg.text.content == textmessage2){
digitalWrite(2,LOW);
}
?

**Comment by mobizt** [comment]
```cpp
if(strcmp(msg.text.content, textmessage1)==0){
   digitalWrite(2,HIGH);
}

if(strcmp(msg.text.content, textmessage2)==0){
   digitalWrite(2,LOW);
}
```

**Comment by pyrismian** [comment]
Thanks
