### ISSUE TITLE
Slow mailcheck with MailClient.readMail-method

### ISSUE THREAD

**Issue by rolandwidmer** [mobizt/ESP-Mail-Client#6]
My program is looking frequently for unread mails in an IMAP-server. If there is an unread mail, it is retrieved almost immediately (200 ms). However if there is NO unread mail, the MailClient.readMail-method needs about 30 seconds and ends up with an error message: "Error, connection lost". If a new mail is arriving within this time window (30s) it is not found, so apparently the method is not doing anything.

Can anybody imagine, what the problem might be?

.
.
.
config.search.criteria = "UID SEARCH NOT SEEN";

void loop() {  
    // Connect to server
    imap.connect(&session, &config);
    imap.selectFolder("INBOX");

    MailClient.readMail(&imap, false);
     
    IMAP_MSG_List msgList = imap.data();   
    for (size_t i = 0; i < msgList.msgItems.size(); i++)     {
        IMAP_MSG_Item msg = msgList.msgItems[i];
        MailClient.setFlag(&imap, atoi(msg.UID), "\\Seen", false);   

        Serial.println("################################");
        Serial.printf("Subject: %s\n", msg.subject);
        Serial.println("################################");
        }

    // Close the session in case the session is still open 
    imap.closeSession();
    imap.empty();
.
.
.

10:11:28.474 -> Logging in...
10:11:28.474 -> C: send imap command, LOGIN
10:11:28.520 -> 
10:11:28.520 -> Selecting the INBOX folder...
10:11:28.520 -> C: open the mailbox folder
10:11:28.614 -> readmail
10:11:28.614 -> 
10:11:28.614 -> Searching messages...
10:11:58.719 -> Error, connection lost

**Comment by mobizt** [comment]
Why open this issue?
