### ISSUE TITLE
Warning in ESP8266

### ISSUE THREAD

**Issue by MCSE-2000** [mobizt/ESP-Mail-Client#65]
Hello,
i get a warning in the library ESP_Mail_Client V1.3.0 when i compile my project in Arduino.
Message:
/mnt/01D1A901D0770EE0/LinuxPortable/arduino/portable/sketchbook/libraries/ESP_Mail_Client/src/wcs/esp8266/ESP8266_TCP_Client.cpp: In member function 'int ESP8266_TCP_Client::send(const char*)':
/mnt/01D1A901D0770EE0/LinuxPortable/arduino/portable/sketchbook/libraries/ESP_Mail_Client/src/wcs/esp8266/ESP8266_TCP_Client.cpp:97:1: warning: control reaches end of non-void function [-Wreturn-type]
   97 | }
      | ^

**Comment by mobizt** [comment]
It has been fixed already since v1.3.0.
