### ISSUE TITLE
Google blocks ESP even if less secure app is turned OFF

### ISSUE THREAD

**Issue by floatAsNeeded** [mobizt/ESP-Mail-Client#66]
Hi!

As per title, I was just wondering why the ESP8266 has been blocked from sign in when trying to log in to the SMPT account. It works fine when I use it in my own network, but if it is a different network from another country in the world, google block the access of the ESP even less secure app is turned off.

I know it doesn't seem secure, but that account is just used as a SMPT account. 

Any suggestions?

**Comment by mobizt** [comment]
This is not library issue. Contact google and ask his policy.
Use [discussions](https://github.com/mobizt/ESP-Mail-Client/discussions) instead of open issue.
