### ISSUE TITLE
5.5.4 Error: Bad NOTIFY parameter syntax

### ISSUE THREAD

**Issue by rclabs-dev** [mobizt/ESP-Mail-Client#74]
**Build tool used:**

- [ ] Arudino
- [ X ] Platformio (Visual Studio Code plugin)
- [ ] Platformio CLI
- [ ] Other

**Board used (ESP32):**

- [ ] ESP8266-based
- [X] ESP32-based

**Other Libraries That are used:**

[env:esp32doit-devkit-v1]
platform = espressif32
board = esp32doit-devkit-v1
framework = arduino
monitor_port = /dev/ttyUSB0
monitor_speed = 115200
upload_port = /dev/ttyUSB0
upload_speed = 115200
lib_deps = 
	openenergymonitor/EmonLib@^1.1.0
	mobizt/ESP Mail Client@^1.3.2

**Description of problem:**
Hi dear,
I try to send e-mail to my postifx, but I receveid the follow error:
< S: 250-mail.rclabs.com.br
< S: 250-PIPELINING
< S: 250-SIZE 10240000
< S: 250-ETRN
< S: 250-AUTH PLAIN LOGIN
< S: 250-AUTH=PLAIN LOGIN
< S: 250-ENHANCEDSTATUSCODES
< S: 250-8BITMIME
< S: 250-DSN
< S: 250 SMTPUTF8
> C: send smtp command, AUTH PLAIN
> C: rcosta
> C: rcosta ************
< S: 235 2.7.0 Authentication successful
> C: send Email
> C: send message header
< S: 250 2.1.0 Ok
< S: 501 5.5.4 Error: Bad NOTIFY parameter syntax
> E: set recipient failed
> C: cleaning SSL connection
Error sending Email, set recipient failed

**Share code snippet to reproduce the issue:**
```yaml
PASTE .cpp / .ino code here
Relevant parto of the code:
 smtp.debug(1);
  smtp.callback(smtpCallback);

  ESP_Mail_Session session;
  session.server.host_name = "xpto.rclabs.com.br";
  session.server.port = 587;
  session.login.email = "rcosta";
  session.login.password = "xpto";
  session.login.user_domain = "";

  SMTP_Message message;
  message.sender.name = "Xpto From";
  message.sender.email = "<xpto@rclabs.com.br>";
  message.subject = "Falta de energia";
  message.addRecipient("Xpto To", "<xpto@yahoo.com.br>");
```

**Additional information and things you've tried:**
I try to remove "<" and ">" in the e-mail address, but occurs the same error.

**Comment by mobizt** [comment]
You can't use [DSN](https://github.com/mobizt/ESP-Mail-Client/blob/265f75e22303d3b7ffbf01b9c13f52eee1c11503/examples/Send_Text/Send_Text.ino#L172) if your SMTP was not support it.
