### ISSUE TITLE
Example of SSL/TLS using a rootCA

### ISSUE THREAD

**Issue by pakalvoltan** [mobizt/ESP-Mail-Client#77]
**Build tool used:**

- [x] Arduino IDE
- [ ] Platformio (Visual Studio Code plugin)
- [ ] Platformio CLI
- [ ] Other

**Board used (ESP32/ESP8266/Arudino):**

- [ ] ESP8266-based
- [x] ESP32-based

**Other Libraries That are used:**

**Description of problem:**
I have successfully used this library to send emails using gmail and SSL/TLS using port 587, but without setting the option to verify the certificate.  However for security reasons it would be good to verify the root CA.  I have tried in several ways to use it, and no connection. I always get in the debug log in my serial console,the following:

>Send command, STARTTLS
> C: send STARTTLS command
220 2.0.0 Ready to start TLS
< S: 220 2.0.0 Ready to start TLS
> C: performing the SSL/TLS handshake
> C: seeding the random number generator
> C: setting up the SSL/TLS structure
> C: cleaning SSL connection
Error, fail to set up the SSL/TLS structure
> E: fail to set up the SSL/TLS structure

It would be great to include an example on how to use the 
session.certificate.verify = true;

how to specify the root certificate and how to specify the other necessary options to be set.

Thank you!

**Share code snippet to reproduce the issue:**
```yaml
PASTE .cpp / .ino code here

```

**Additional information and things you've tried:**

  /* Set the session config */
  session.server.host_name = SMTP_HOST;  // This is "smtp.gmail.com"
  session.server.port = SMTP_PORT;   // This is 587
  session.login.email = AUTHOR_EMAIL;  
  session.login.password = AUTHOR_PASSWORD;
  session.login.user_domain = MY_DOMAIN;  // here the real domain being used
  session.certificate.verify = true;
  session.certificate.cert_data = GSR2_PEM;   // This is a pem of the GlobalSign R2 CA PEM

**Comment by mobizt** [comment]
This option will include in the specific platform example updates.

Because the certificate verification in other support platform e.g.  SAMD21 using WiFiNINA firmware is different because arduino team manage the cert stores differently, the options in the session config for certificate data verification are for ESP8266 and ESP32 only.
