### ISSUE TITLE
setFlag still not working?

### ISSUE THREAD

**Issue by Quasimodem12** [mobizt/ESP-Mail-Client#9]
Hello,
I replaced the previous library with version 1.0.8. Unfortunately, upon attempting to verify the Set_Flag example, I encounter the following:

Set_Flags:202:65: error: no matching function for call to 'ESP_Mail_Client::setFlag(IMAPSession&, int, const char [16], bool)'
     if (MailClient.setFlag(imap, 100, "\\Seen \\Answered", false))

Not sure if I'm doing something incorrectly...
thank you.

**Comment by mobizt** [comment]
Thanks for the issue.

Due to typo in this example, it should be

```cpp
if (MailClient.setFlag(&imap, 100, "\\Seen \\Answered", false))
```

**Comment by Quasimodem12** [comment]
It worked, thank you very much!
